### ISSUE TITLE
Show more than 25 saved comments

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1093]
### Describe the problem and steps to reproduce it:

- Sign in
- Add more than 25 comments to a file
- Refresh the page

### What happened?

Only the first 25 saved comments are shown

### What did you expect to happen?

All saved comments should be shown

### Anything else we should know?

Rendering saved comments was added in https://github.com/mozilla/addons-code-manager/issues/713

**Comment by alexkayabula** [comment]
Hello @kumar303, I am trying to reproduce this issue but when I run the local app and sign in I keep getting this error `Unexpected status for GET /reviewers/addon/494431/versions/1532144/?lang=en-US: 403`.
It is associated with `{"detail":"You do not have permission to perform this action."}`.
Any help is much appreciated.

**Comment by ioanarusiczki** [comment]
@kumar303 

Frontend testing:

I verified it with https://code.addons-dev.allizom.org/en-US/browse/618280/versions/1689601/?path=popup%2Fcss%2Fbootstrap.min.css

I don't know if there's a limit, but I went up to 50 comments on different files. The number is updated correctly and comments are displayed after a page refresh. 

I did some backend testing too :

I posted a comment using the [API ](https://addons-dev.allizom.org/api/v4/reviewers/addon/618280/versions/1689601/draft_comments/)which was created with a 201 status. The frontend on dev counted it too as being available (the 49th comment made) yet it is not displayed because the `lineno`:8 does not exist for the file
https://code.addons-dev.allizom.org/en-US/browse/618280/versions/1689601/?path=popup%2Fcss%2Fbootstrap.min.css
POST 
`{   "comment":"testing the plus 49 comments",
	"filename":"popup/css/bootstrap.min.css",
	"lineno":8
}`

The same thing happens if I don't specify the path of the file correctly.

`{   "comment":"testing the plus 51 comments",
	"filename":"bootstrap.min.css",
	"lineno":8
}`

![Comments51](https://user-images.githubusercontent.com/33448286/68132163-e35eed00-ff26-11e9-8e21-9e162f3c734b.png)

I think this is a known API limitation (it won't detect if code line exists or not, same for a file).

**Comment by kumar303** [comment]
Thanks.

> I posted a comment using the [API ](https://addons-dev.allizom.org/api/v4/reviewers/addon/618280/versions/1689601/draft_comments/)which was created with a 201 status. The frontend on dev counted it too as being available (the 49th comment made) yet it is not displayed because the `lineno`:8 does not exist for the file
> https://code.addons-dev.allizom.org/en-US/browse/618280/versions/1689601/?path=popup%2Fcss%2Fbootstrap.min.css
> POST
> `{ "comment":"testing the plus 49 comments", "filename":"popup/css/bootstrap.min.css", "lineno":8 }`
> 

Can you file an `addons-server` bug for that? It should not be possible to comment on a line number that doesn't exist.

> The same thing happens if I don't specify the path of the file correctly.

Yeah, this API bug is tracked in https://github.com/mozilla/addons-server/issues/11813

**Comment by ioanarusiczki** [comment]
@kumar303 
Done https://github.com/mozilla/addons-server/issues/12790

I can mark this issue verified on dev with FF70(Win10).
