### ISSUE TITLE
When selecting a new version the file path is not preserved anymore

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1094]
Followup for https://github.com/mozilla/addons-code-manager/issues/777

STR:
1. Go to a compare page for an add-on to view a specific file such as 
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474840/?path=background.js
2. Select the oldest version 10.30.2 for Old version field - page will reload and will show the same file
3. Select the next version available for New version field - 10.30.3 and observe the screen

Expected result:
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474840/?path=background.js is reloaded 

Actual result:
Page displays manifest.json

Notes:
Reproducible on AMO dev and AMO stage with FF69 (Win10). 

![regression](https://user-images.githubusercontent.com/33448286/66044180-a7042f80-e529-11e9-93ef-88755ed292b4.gif)

**Comment by kumar303** [comment]
Thanks for filing. I noticed this too when reviewing https://github.com/mozilla/addons-code-manager/pull/1025 but the same problem existed on the master branch at the time.

@mirefly would you like to take a look at this since you're familiar with the path switching now?

**Comment by mirefly** [comment]
@kumar303  The cause is that [selectedPath](https://github.com/mozilla/addons-code-manager/blob/master/src/reducers/versions.tsx#L201) is in a specific `version`. Therefore, loading a new `version` (selecting a different new version in compare mode) will have a different selected file path.

One idea in my mind is to add a new key `versions.lastVersionId` in Redux store, so that we can access the `selectedPath` from the last `version` after changing the "new version" in UI. We will need to check if the previous `selectedPath` exists in the new `version`, if the path does not exist, we do not change the `selectedPath` in the new `version`. (We probably also need to recover `expandedPaths` from the last version, otherwise, all folds will be closed when selecting new version).

**Comment by kumar303** [comment]
There is an important use case for this:
- Review an offending line of code in a file
- Wonder where the offending line of code was introduced
- Use the version selector to quickly go back through earlier versions to look for the same line
