### ISSUE TITLE
Add API support for deleting a comment

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1114]
Add API changes needed to delete a comment. See https://github.com/mozilla/addons-code-manager/issues/714 for the UI.

**For QA**: this change will affect all API calls so please do a rough sanity check on any feature involving API calls (browsing, comparing, viewing linter messages, log in, log out)

**Comment by ioanarusiczki** [comment]
@kumar303 
I verified on dev with FF69(Win10)
Browse
https://code.addons-dev.allizom.org/en-US/browse/492486/versions/1529211/
Compare
https://code.addons-dev.allizom.org/en-US/compare/492486/versions/1529211...1688395/
- no errors in the network for the APIs while navigating through files in Browse and Compare, files load and I did not find anything unusual while browsing except for https://github.com/mozilla/addons-code-manager/issues/1132 which I do not think it is a regression caused by this issue.  In case it's a dupe sorry for re-filing( because it's somehow familiar).
