### ISSUE TITLE
Disable trimming of large (slow) diffs

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1230]
### Describe the problem and steps to reproduce it:

* Load a large diff (see https://github.com/mozilla/addons-code-manager/issues/971) in compare mode

### What happened?

The diff should not be truncated

### What did you expect to happen?

The diff is currently truncated as an attempt to speed up the page

### Anything else we should know?

We'd like to show the entire diff as a workaround to https://github.com/mozilla/addons-code-manager/issues/971 which is about broken navigation due to the trimmed file.

**Comment by bobsilverberg** [comment]
@kumar303 I have some questions:

- Have we considered doing something similar to what was suggested at https://github.com/mozilla/addons-code-manager/issues/967#issue-471794593, i.e., showing the user a message telling them they need to load the whole file in order to navigate between diffs? Or would we consider that to be terrible UX for this use case?
- Is our intention to permanently remove this speed optimization, or is this something temporary until we have a better solution?
- If this is considered temporary, should we disable the feature via code, as opposed to actually deleting all of the code that supports the feature, the latter of which is probably the "appropriate" thing to do?

**Comment by bobsilverberg** [comment]
@wagnerand Kumar and I were discussing this via IRC, and I was wondering whether we want to consider disabling trimming of files by default in Browser mode as well. I recall that that was causing some issues with linter message navigation, but perhaps that issue is not as major as this one?

As the code for this is somewhat centralized, if we do think we want to disable it in both places it would make sense to do that all at once. If, on the other hand, we think we might only need to disable it for Compare view, then that's what I'll do.

**Comment by kumar303** [comment]
@wagnerand in our meeting you mentioned that loading a slow page by default would negate the benefits of later toggling the button to truncate slow pages since the page would have been loaded into memory. I forgot to mention that this is not the case because loading the page into memory doesn't make the slowness go away. 

Thus, I think it would make sense to keep the toggle button around, at least until we decide about what to do permanently.

**Comment by wagnerand** [comment]
> @wagnerand Kumar and I were discussing this via IRC, and I was wondering whether we want to consider disabling trimming of files by default in Browser mode as well. I recall that that was causing some issues with linter message navigation, but perhaps that issue is not as major as this one?

I was leaning towards keeping it enabled by default in browse mode because reviewers have a different workflow. In diff mode, reviewers focus on diffs and often use keyboard shortcuts to jump from one diff to the next to avoid scrolling. In browse mode, the focus is often more on a sequential read from top to bottom. There, reviewers would see the notice and expand if necessary. Also, in browse mode, we would (only) skip linter messages, since there are no diffs, and many of the linter messages are targeted more at developers than at reviewers.


> @wagnerand in our meeting you mentioned that loading a slow page by default would negate the benefits of later toggling the button to truncate slow pages since the page would have been loaded into memory. I forgot to mention that this is not the case because loading the page into memory doesn't make the slowness go away.

I am not sure I follow what you are saying. What I meant was that with slow mode enabled, you have to wait until the full file is loaded, only then can you trim it. But why would you trim it at that point, given that you have the entire file now?

**Comment by bobsilverberg** [comment]
> 
> I was leaning towards keeping it enabled by default in browse mode because reviewers have a different workflow. In diff mode, reviewers focus on diffs and often use keyboard shortcuts to jump from one diff to the next to avoid scrolling. In browse mode, the focus is often more on a sequential read from top to bottom. There, reviewers would see the notice and expand if necessary. Also, in browse mode, we would (only) skip linter messages, since there are no diffs, and many of the linter messages are targeted more at developers than at reviewers.
> 

Ok, thanks. For now we will just change the default for Compare mode.

> 
> I am not sure I follow what you are saying. What I meant was that with slow mode enabled, you have to wait until the full file is loaded, only then can you trim it. But why would you trim it at that point, given that you have the entire file now?

I believe what @kumar303 meant is that even after the file is fully loaded, the UI can remain slow for a large file. So trimming an already loaded file can help with the performance of the UI.

**Comment by wagnerand** [comment]
> I believe what @kumar303 meant is that even after the file is fully loaded, the UI can remain slow for a large file. So trimming an already loaded file can help with the performance of the UI.

Ah ok. We can leave the button around in case someone wants to enable trimming for diffs.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev. 
The compare view is now displaying the whole content by default, which makes navigation between diff changes possible (though very slow).

![image](https://user-images.githubusercontent.com/31961530/69329583-0b09c100-0c5a-11ea-8b7e-f63f9b3df51f.png)


The browse view continues to show trimmed content.
