### ISSUE TITLE
Truncate file content based on number of characters in the CodeView

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1347]
As discussed in the comments below, it is believed that all we need to do to address performance issues with large files is to truncate the contents of any file that is above a particular threshold. We do not think that we need to disable highlighting for this truncated file.

The contents should include an indication that the file was truncated (e.g., a comment added by code-manager), and a button should be available to view the whole file. The latter part is already implemented via `SlowPageAlert`.

The suggested limit for number of characters is 3000. If any file is larger than that then only the first 2000 characters of the file will be shown.

Note that follow-ups should be filed to do the same for the Compare page, as well as to remove the code that disables highlighting when a file is truncated.

**Comment by willdurand** [comment]
@bobsilverberg rethinking this problem, what's the point of having partial files in the end? Does that help the reviewer when they cannot read the last part of a line of code or the end of a function?

How about we don't show any code at all and only display the `SlowAlert`, maybe with a bigger button to show the content anyway? That's what GitHub does and I like it.

**Comment by bobsilverberg** [comment]
> @bobsilverberg rethinking this problem, what's the point of having partial files in the end? Does that help the reviewer when they cannot read the last part of a line of code or the end of a function?
> 
> How about we don't show any code at all and only display the `SlowAlert`, maybe with a bigger button to show the content anyway? That's what GitHub does and I like it.

My thought is that seeing at least part of the code gives the reviewer more information to allow them to decide if they need to see all the code or not. Even if we truncate lines at 500 chars, that should be enough to give the reviewer a clue about whether they should try to examine the whole file or not.

If we don't do this, and just display nothing but a message, what information are we giving them that would allow them to decide whether to view the whole file or not?

**Comment by willdurand** [comment]
It tells them that the file is large and that it is going to be slow to render in the browser but I can see how giving an excerpt could be useful.

I am wondering whether we should try to find good enough numbers or make things faster by providing a "fixed" excerpt (rather than a partial content). Sadly, the logic to display the entire content triggers a full page reload. Reviewers have to wait quite some time 2 times then..

**Comment by bobsilverberg** [comment]
> It tells them that the file is large and that it is going to be slow to render in the browser but I can see how giving an excerpt could be useful.
> 
> I am wondering whether we should try to find good enough numbers or make things faster by providing a "fixed" excerpt (rather than a partial content). Sadly, the logic to display the entire content triggers a full page reload. Reviewers have to wait quite some time 2 times then..

@willdurand I'm not sure where we stand here. It seems like this current approach is a reasonable way of providing an "excerpt" for now. Do you still feel this approach is not correct, and if so, what specific suggestions do you have for doing something different? I am inclined to implement this change, and then perhaps go back to the users to see how useful/helpful it is.

**Comment by willdurand** [comment]
Truncating a file content makes sense because it still gives valid code but when we truncate lines, then the content does not make sense anymore. This is why I thought the number of characters was a better metric because then we would show some valid content.

I understand why truncating lines will make things faster and maybe this is the way to go (that is why I r+ed the patch) but I personally don't like this approach. We are already showing partial yet valid content and soon, we'll show partial *and* potentially invalid content..

I don't have an immediate solution if rendering one line of 2000 characters makes our app slow, but I think rendering 2000 characters only would be good enough for reviewers. And I think that'd be a better approach if we included a big button to "show this file entirely".

**Comment by willdurand** [comment]
@bobsilverberg I tried to come up with a simple patch to illustrate what I wrote above: https://gist.github.com/45f5a26cd26cdb08a8f706bd9a04ce7b

It loads fast for me locally (in FF :p) and it still gives useful information. In addition, that is uncomplicated. What do you think? Could you give this patch a try and tell me how you feel?

**Comment by bobsilverberg** [comment]
> @bobsilverberg I tried to come up with a simple patch to illustrate what I wrote above: [gist.github.com/45f5a26cd26cdb08a8f706bd9a04ce7b](https://gist.github.com/45f5a26cd26cdb08a8f706bd9a04ce7b)
> 
> It loads fast for me locally (in FF :p) and it still gives useful information. In addition, that is uncomplicated. What do you think? Could you give this patch a try and tell me how you feel?

I assume this is in place of PR #1348?

Looking at the patch, is it also intended to undo the change that prevented wide files from being highlighted? I.e, we would just truncate all content above 2000 chars but still highlight what we have?

**Comment by willdurand** [comment]
> Looking at the patch, is it also intended to undo the change that prevented wide files from being highlighted? I.e, we would just truncate all content above 2000 chars but still highlight what we have?

Yes, I tried with different jquery files and that loaded fast enough.

My main idea is that it allows reviewers to move fast between files and when they find a file of interest, they will have to load the full content anyway (which is slow). It only reduces the time to "explore" add-on files, which is valid because otherwise we provide false expectations to the reviewers (which is to show part of a file). I think it is better to not set false expectations (that is: we only load a preview of a slow-ish file).

Once we have that, we can try to address slowness when viewing a file entirely. One first improvement could be to render the content without reloading the page (I don't remember why we need a full page reload for that).

I also understand why we tried to address performance issues by truncating a file. This made sense back then. Now we think about truncating lines too, also potentially adjusting the number of lines/characters per line, etc. This seems complicated for little value because, IMO, the "partial file" feature should only be used to allow reviewers to answer this question: do I (reviewer) need to see the full content of this file or can I skip it?

I know the patch looks naive but it took me quite some time to reach these conclusions. Seeing the reviewers in action the other day made me realize how they were using this tool.

**Comment by bobsilverberg** [comment]
Fair enough. If it works in all cases where things are slow now, I agree it seems like a good approach. Should we also undo the work that landed in https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37, or do you think it's fine to keep that in place? We'd still need to add a message to indicate that the file is not being highlighted.

**Comment by willdurand** [comment]
> Fair enough. If it works in all cases where things are slow now, I agree it seems like a good approach. Should we also undo the work that landed in [112e2eb](https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37), or do you think it's fine to keep that in place? We'd still need to add a message to indicate that the file is not being highlighted.

I am not sure. For the few add-ons I've tried, syntax highlighting was not a problem, especially when rendering 2k or 3k characters.

**Comment by bobsilverberg** [comment]
> > Fair enough. If it works in all cases where things are slow now, I agree it seems like a good approach. Should we also undo the work that landed in [112e2eb](https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37), or do you think it's fine to keep that in place? We'd still need to add a message to indicate that the file is not being highlighted.
> 
> I am not sure. For the few add-ons I've tried, syntax highlighting was not a problem, especially when rendering 2k or 3k characters. I'd go for simplifying the whole "partial content" feature personally.

Ok, I guess we can leave it in place for now then. I suppose the upshot of this conversation is that we should change the algorithm for when a file gets "shortened" to be based solely on number of characters, and we should add an indication inside the code itself that the code has been truncated. Do you agree that that is how we should proceed?

**Comment by willdurand** [comment]
> Ok, I guess we can leave it in place for now then. I suppose the upshot of this conversation is that we should change the algorithm for when a file gets "shortened" to be based solely on number of characters, and we should add an indication inside the code itself that the code has been truncated. Do you agree that that is how we should proceed?

Yep, I do. If you agree, I'd like to adopt this approach to fix all kind of "truncated content" issues. We should make sure to make it obvious that: (1) the content is truncated and (2) a button can reveal the full content.

**Comment by bobsilverberg** [comment]
> > Ok, I guess we can leave it in place for now then. I suppose the upshot of this conversation is that we should change the algorithm for when a file gets "shortened" to be based solely on number of characters, and we should add an indication inside the code itself that the code has been truncated. Do you agree that that is how we should proceed?
> 
> Yep, I do. If you agree, I'd like to adopt this approach to fix all kind of "truncated content" issues. We should make sure to make it obvious that: (1) the content is truncated and (2) a button can reveal the full content.
> 
> Edit: this could be a good start: [gist.github.com/willdurand/45f5a26cd26cdb08a8f706bd9a04ce7b](https://gist.github.com/willdurand/45f5a26cd26cdb08a8f706bd9a04ce7b) (but we'll have to remove some code too)

Ok, I'm going to rename this issue to reflect these new requirements, and update the description as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The Browse pages seem to be working as described above on FF72(Win10):
 - the highlighting is enabled again.
- the long code lines are truncated at 2000 chars (if they're longer than 3000 chars).

Examples: 
https://code.addons-dev.allizom.org/en-US/browse/618541/versions/1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css
https://code.addons-dev.allizom.org/en-US/browse/618525/versions/1689955/?allowSlowPages=false&path=src%2Fvue.bundle.js

- the files with many code lines will be truncated at 2000 chars (if they're longer than 3000 chars).

Examples:
https://code.addons-dev.allizom.org/en-US/browse/618541/versions/1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-signin.styles.css
https://code.addons-dev.allizom.org/en-US/browse/618525/versions/1689955/?allowSlowPages=false&path=src%2Faction%2Fstyle.bundle.css
