### ISSUE TITLE
The code overview is not showing the new added lines 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1400]
Followup for https://github.com/mozilla/addons-code-manager/issues/920

STR:
1. Load https://code.addons-dev.allizom.org/en-US/compare/618623/versions/1690065...1690066/?path=node_modules%2Fweb-animations-js%2Fsrc%2Fscope.js
2. Click the compare buttons and change the old version to `5.1.3`
3. Observe the code overview 

Expected result:
The code overview should show green lines.

Actual result:
The lines are light grey - not showing the changes (added lines of code). Only after clicking on one of the lines they will change the color. 

Notes:
This issue is reproducible on dev with FF72(Win10). 

![green lines not visible](https://user-images.githubusercontent.com/33448286/72715313-ec03ae80-3b78-11ea-955d-6c270ae1236e.gif)

**Comment by bobsilverberg** [comment]
I’ve been looking into this and I’m a bit stumped at the moment. @mirefly and/or @willdurand (when you get back from leave), I was wondering if you might be able to take a look and see if you have any advice.

I have identified the fact that `VersionFileViewer` is being re-rendered when the new diff is loaded after switching the versions in the Compare dialog, but that `CodeOverview` is not re-rendering which is why the colours are not appearing. `CodeOverview` is re-rendered once, but at that point we haven’t loaded the new diff yet, so the app believes there are no changes to highlight. After the new diff is loaded, `VersionFileViewer`’s render is triggered, and inside that render we [calculate a new value for `insertedLines`](https://github.com/mozilla/addons-code-manager/blob/master/src/components/VersionFileViewer/index.tsx#L75-L78), which is [passed as a property into `CodeOverview`](https://github.com/mozilla/addons-code-manager/blob/master/src/components/VersionFileViewer/index.tsx#L132). I would have expected that when the value for `insertedLines` changes, that would trigger a re-render of `CodeOverview`, but it does not. So perhaps this isn’t all wired together in a way that will always work.

Interestingly, it does all seem to work when we navigate to a different file. It’s just this one case when we change the versions being compared via the Compare dialog that it doesn’t work. So I’m not sure if it’s a problem with the way `VersionFileViewer` and `CodeOverview` are wired up, or a problem with what we do when switching versions with the Compare dialog. All we do when switching versions is to push a new URL using [`history.push`](https://github.com/mozilla/addons-code-manager/blob/master/src/components/VersionChooser/index.tsx#L153-L157), and , as mentioned above, this *does* trigger a re-render of `CodeOverview`, but at that point the new diff has not been loaded yet. What we need is for a re-render of `CodeOverview` to be triggered after the diff has been loaded.

**Comment by mirefly** [comment]
We had seen a similar thing before  https://github.com/mozilla/addons-code-manager/pull/1154#pullrequestreview-306809886. The following patch works, but it may be not a good idea to pass the string of a long list `insertedLines`.
```diff
diff --git a/src/components/CodeOverview/index.tsx b/src/components/CodeOverview/index.tsx
index ad21a4c..bd18c51 100644
--- a/src/components/CodeOverview/index.tsx
+++ b/src/components/CodeOverview/index.tsx
@@ -332,11 +332,13 @@ export class CodeOverviewBase extends React.Component<Props, State> {
 
   render() {
     const { overviewHeight } = this.state;
-    const { version } = this.props;
+    const { insertedLines, version } = this.props;
 
     return (
       <LinterProvider
-        key={overviewHeight ? String(overviewHeight) : ''}
+        key={
+          (overviewHeight ? String(overviewHeight) : '') + String(insertedLines)
+        }
         versionId={version.id}
         validationURL={version.validationURL}
         selectedPath={version.selectedPath}

```

**Comment by bobsilverberg** [comment]
Thanks @mirefly! So, looking at #1154, the idea is to force a remount when `insertedLines` changes? Is that what makes it re-render? I suppose we could hash `insertedLines`, which would make it smaller and still cause it to be different when the contents of `insertedLines` changes. Does that sound like a reasonable idea?

**Comment by mirefly** [comment]
> the idea is to force a remount when insertedLines changes? Is that what makes it re-render? 

Yes.

> I suppose we could hash insertedLines, which would make it smaller and still cause it to be different when the contents of insertedLines changes.

Yes, that makes sense. But I feel that maybe we do not need hashing. Here is one idea in my mind:
- Let [`insertedLines` ](https://github.com/mozilla/addons-code-manager/blob/c0316f414a023411f8ddc94911d86174f064fd53/src/components/VersionFileViewer/index.tsx#L75-L78)to be `undefined` if the `compareInfo &&compareInfo.diff`

**Comment by mirefly** [comment]
I had a second thought. We do not need the first step. Just passing `insertedLines.length` as key might be enough.
> Let insertedLines to be undefined if the compareInfo &&compareInfo.diff is undefined

```diff
diff --git a/src/components/CodeOverview/index.tsx b/src/components/CodeOverview/index.tsx
index ad21a4c..b06cfe2 100644
--- a/src/components/CodeOverview/index.tsx
+++ b/src/components/CodeOverview/index.tsx
@@ -332,11 +332,13 @@ export class CodeOverviewBase extends React.Component<Props, State> {
 
   render() {
     const { overviewHeight } = this.state;
-    const { version } = this.props;
+    const { insertedLines, version } = this.props;
 
     return (
       <LinterProvider
-        key={overviewHeight ? String(overviewHeight) : ''}
+        key={`${overviewHeight ? String(overviewHeight) : ''};${String(
+          insertedLines.length,
+        )}`}
         versionId={version.id}
         validationURL={version.validationURL}
         selectedPath={version.selectedPath}
```

**Comment by bobsilverberg** [comment]
@mirefly That makes sense, but I can't help feeling like this is a hack. I wonder if it would make more sense to use `mapStateToProps` to bring in `insertedLines`, and whether doing that might make the component re-render when `insertedLines` changes? I'll give that a try and see if it works.

**Comment by bobsilverberg** [comment]
Hmm, even that didn't work, which seems really odd. I guess we can go with the `key` route, but I don't really understand why `mapStateToProps` isn't working to make the `CodeOverview` re-render when the redux state changes for `compareInfo`.

**Comment by bobsilverberg** [comment]
@mirefly I figured it out. It has to do with the way we're passing the render function into `LinterProvider`. We had to do something similar in [`CodeView`](https://github.com/mozilla/addons-code-manager/blob/master/src/components/CodeView/index.tsx#L259-L262) so that *it* would re-render when state changed. If we do the same thing in `CodeOverview` it works!  I'll create a patch.

**Comment by mirefly** [comment]
My understanding is: anonymous function acts like a random value and force `CodeOverview` to re-render. In other words, the React element returned by `render()` is always treated as different from the last rendered one, and requires updating UI even though it does not need sometimes.

As long as it does not hurt performance, I am OK with using arrow function in this case.

**Comment by ioanarusiczki** [comment]
@bobsilverberg this is fixed on dev - FF73(Win10)

![green added lines](https://user-images.githubusercontent.com/33448286/74828296-8e998380-5317-11ea-9537-dfba6643bbbf.gif)
