### ISSUE TITLE
Load the initial path - manifest.json on versions with deleted files

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1418]
Followup for https://github.com/mozilla/addons-code-manager/issues/1405#issuecomment-579800035

STR;
1. Load https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=chrome.manifest
2. Go to the new version's Browse page by clicking the "Compare Versions" button 
3. Observe the page

Actual result:
Unexpected status for GET /reviewers/addon/7560/versions/1688305/?file=install.rdf&lang=en-US: 404

Expected result:
The manifest.json file loads for the Browse page.

Notes:
The same thing could be done when the Browse page of an old version is accessed https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=mozilla-recommendation.json for a file that does not exist in that version. Right now the page is returning a 500 error message - server issue was filed https://github.com/mozilla/addons-server/issues/13374#issuecomment-579785782

![this one](https://user-images.githubusercontent.com/33448286/73459314-4f62bd00-437f-11ea-94e7-8c51ca27833a.gif)

![that one](https://user-images.githubusercontent.com/33448286/73459295-483baf00-437f-11ea-9d9b-7b67d5b53581.gif)

**Comment by bobsilverberg** [comment]
Just to clarify, what is being asked here is that, if we browse a version with a path in the URL which points to a file that does not exist in that version, we should just display the default file (which is `manifest.json`) instead.

@ioanarusiczki Is that correct?

@wagnerand / @mirefly What do you think?

**Comment by wagnerand** [comment]
I think it's fine to just keep displaying 404 in the described case.

**Comment by bobsilverberg** [comment]
> I think it's fine to just keep displaying 404 in the described case.

I'm not sure the description accurately reflects the problem. It seems that the whole UI is questionable when this happens. For example, if you follow the STR, you end up with a page that looks like this:

<img width="983" alt="Screenshot 2020-02-04 14 46 31" src="https://user-images.githubusercontent.com/142755/73780833-37af7e00-475d-11ea-9b61-092b77eae75a.png">

Note that in addition to the error at the top of the page, the code area says "Loading content..." (even though it isn't actually loading content), and the file tree remains unchanged from the compare screen. That is, the file list contains files that have been deleted and are not part of this version. If a user were to click on `install.rdf`, for example, another 404 error would occur. This doesn't seem like a good state to leave the user in, which is why it seems like displaying a file known to be part of the current version would be a better idea.

**Comment by mirefly** [comment]
>  the file tree remains unchanged from the compare screen

Yeah, I just saw this. The fire tree really needs to be updated.

I personally prefer falling back to 'manifest.json', so that user does not need to close the 404 alert message. If we would like to have this 404 message displayed to warn the user that the file does not exist, we might need to disable the loading spinner at least.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Either to fall-back to manifest.json or to display a [message](https://github.com/mozilla/addons-code-manager/issues/1405#issuecomment-579760860) on the page with a link instead of a continuous loading state maybe?

**Comment by wagnerand** [comment]
I agree we should fix it, but I don't see it as something very urgent. I would probably change it to P5 if it wasn't for 

> ...the file list contains files that have been deleted and are not part of this version.

**Comment by mirefly** [comment]
Filed another issue #1421 to track the issue about the file list.
