### ISSUE TITLE
Disable `react/no-multi-comp` ESLint rule

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#154]
From: https://github.com/mozilla/addons-code-manager/pull/137#discussion_r254381556

---

Let's disable `react/no-multi-comp` rule globally since we can't rely on it anyway (i.e. we always disable it, in each file)

**Comment by kumar303** [comment]
I can see how maybe it's a good rule to encourage people to only put one component in something like `src/components/MyComponent/index.tsx` but I don't feel strongly about that. In `addons-frontend` it was nice having a separate `tests` directory because we could drop lint rules in `tests/.eslintrc`.

**Comment by willdurand** [comment]
Thinking about it again, helped with a quick `rg no-multi-comp`, I don't think we need to do anything right now as this rule isn't problematic.
