### ISSUE TITLE
Do not reload full page when switching `allowSlow`

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#1540]
I noticed that the page is fully reloaded when we switch between the truncated and non-truncated view.

If there is no particular reason to do this, let's see if we can avoid that and instead just reload the file contents.

**Comment by willdurand** [comment]
I thought we had an issue about that already (because [I mentioned this problem a few months ago already](https://github.com/mozilla/addons-code-manager/issues/1347#issuecomment-566638766)) but no, so thanks for filing this one.

> If there is no particular reason to do this, let's see if we can avoid that and instead just reload the file contents.

I personally don't see any reason that forces us to perform a full reload and I think client side navigation would help a bit here.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I don't see the pages fully reloading. Sometimes it may take a while to see the other view but the transition is smoother than it used to be until now. 
Here's an example:

![not reloading fully](https://user-images.githubusercontent.com/33448286/79989665-cc05c300-84b8-11ea-9f3f-51efa48c93f5.gif)

Works on both: truncation of minified files and code lines.
Verified on dev with FF75(Win10).
