### ISSUE TITLE
Retrieve only file information when that's all we need

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1574]
~~Depends on https://github.com/mozilla/addons-code-manager/issues/1587~~

Every time code manager retrieves information for a specific file, all of the version information, including all of the entries for the version, is returned. This represents a lot of data being returned to the client that is unneccesary, and likely contributes to some of the API slowness we are seeing.

With the landing of https://github.com/mozilla/addons-server/pull/14163, the Browse and Compare APIs now support a `file_only` param. We should update code manager to use those params when we already have version information.

**Comment by willdurand** [comment]
> This represents a lot of data being returned to the client that is unneccesary, and likely contributes to some of the API slowness we are seeing.

I would be interested in knowing how we came to these conclusions?

> the API slowness we are seeing.

I'd argue that code-manager isn't necessary slow because of the API. Assuming the API was very responsive (like 0ms to return any content), code-manager would still be slow because of the amount of information to display.

> When mozilla/addons-server#14163 lands there will be new endpoints that can be used to request just file information. This issue is about updating code manager to use thos endpoints when we already have version information. It will likely be implemented as a number of smaller issues.

I thought the idea was to add a query parameter to the **existing** endpoints instead of creating new ones (which requires work in both places)?

**Comment by bobsilverberg** [comment]
> > This represents a lot of data being returned to the client that is unneccesary, and likely contributes to some of the API slowness we are seeing.
> 
> I would be interested in knowing how we came to these conclusions?
> 

We have been tracking the amount of time API requests take, and I reported a number of particularly slow requests via https://github.com/mozilla/addons-server/issues/13983. I can see now that there are not any comments from anyone added to that, but my recollection is that a chat via Matrix indicated that at least part of the problem was believed to be coming from this issue. This was also discussed at https://github.com/mozilla/addons-server/issues/13984#issuecomment-616445329, and again the impression was that this was something that would improve performance.

I also opened https://github.com/mozilla/addons-server/issues/14019, which is about pre-calculating the entries, but it was suggested (again, maybe via Matrix) that I tackle this issue first, perhaps because it's a bit simpler to address.

> 
> I'd argue that code-manager isn't necessary slow because of the API. Assuming the API was very responsive (like 0ms to return any content), code-manager would still be slow because of the amount of information to display.
>

That is absolutely correct, but it doesn't change the fact that the API responses are often quite slow, and therefore that is also something that can/should be improved. Will it solve all the problems? No. Is it worth doing? Yes. Should we be prioritizing addressing the code-manager rendering issue via windowing or infinite scroll instead of doing this? Maybe. 

When I filed https://github.com/mozilla/addons-server/issues/14020, @diox asked if I'd be willing to take on both the server and code-manager changes required, and I said sure, which brings us here. There are lots of different things that could be done to help performance in a number of different ways, but we aren't in a position to do all of them at once. 

In addition to the windowing and infinite scroll options, another thing that was discussed quite some time ago was trying to use a time-based solution for truncation, so we could always attempt to display a full file, and fall back to a truncated file if rendering took more than a set amount of time. I'm not sure if that's possible, but it's yet another item on the list.

> > When [mozilla/addons-server#14163](https://github.com/mozilla/addons-server/pull/14163) lands there will be new endpoints that can be used to request just file information. This issue is about updating code manager to use thos endpoints when we already have version information. It will likely be implemented as a number of smaller issues.
> 
> I thought the idea was to add a query parameter to the **existing** endpoints instead of creating new ones (which requires work in both places)?

We discussed this at length this morning and I do think it makes sense to just add a query param to the existing endpoints, but there will still be work required in code manager to make use of these. So we cannot avoid having work in both places.

I will update the description of this issue once we know for sure what changes are going to land for the APIs.

**Comment by willdurand** [comment]
Thanks for the reply.


> We discussed this at length this morning and I do think it makes sense to just add a query param to the existing endpoints, but there will still be work required in code manager to make use of these. So we cannot avoid having work in both places.

Yes, my previous comment was left before our discussion. I left two comments to be sure that one of them would be seen :) I understand the need to make changes in code-manager and that is certainly a good idea.

> In addition to the windowing and infinite scroll options, another thing that was discussed quite some time ago was trying to use a time-based solution for truncation, so we could always attempt to display a full file, and fall back to a truncated file if rendering took more than a set amount of time. I'm not sure if that's possible, but it's yet another item on the list.

Right. I think that's an interesting idea but windowing/infinite scroll will likely fix all our existing problems now and we'll forget about perf issues soon enough :D I don't see any other way to solve the existing perf issues otherwise.

**Comment by diox** [comment]
> I'd argue that code-manager isn't necessary slow because of the API. Assuming the API was very responsive (like 0ms to return any content), code-manager would still be slow because of the amount of information to display.

If API isn't very responsive (like 10s or more to return any content) code-manager *will* be slow :)

**Comment by diox** [comment]
>> This represents a lot of data being returned to the client that is unneccesary, and likely contributes to some of the API slowness we are seeing.
>
> I would be interested in knowing how we came to these conclusions?

To clarify, the actual thing we noticed:
- From data in GA, we found some API calls were super slow
- We can reproduce that slowness by calling them. We noticed that they weren't slow on subsequent calls
- We concluded it was because they were fetching all file entries every time even when we didn't need them
- That lead to this bug and the addons-server ones being filed

The extra data transfer being avoided is just a bonus here - the main problem is fetching the file entries on the server side when we don't need them in the first place. Technically, we will need the file entries for at least one of the calls so at least one API call will still be slow (*), but because the calls happen in parallel not fixing this could still in some cases result in a slowdown of all API calls if the cache isn't populated in time.

(*) We discussed pre-populating file entries in a cache stored with the git commit or something for this. The fact that it's done in-request is a main source of pain, since it means a lot of IO on EFS.

**Comment by bobsilverberg** [comment]
@willdurand Now that https://github.com/mozilla/addons-server/issues/14020 has landed, I plan on working on this issue to make use of the new params. You seemed concerned in your comments that maybe we shouldn't be working on this at all, and instead focussing on solving the perf issues inside of code manager. I agree that that should be a priority after this. You indicated that you did some experimentation with react-window, and I recall that @mirefly also said he'd done some work. There's also the idea of using inifinte scroll instead. Do you want to set up a brief meeting to discuss these, let me know where your work stands, and come up with a path to move forward with this?

**Comment by willdurand** [comment]
> @willdurand Now that [mozilla/addons-server#14020](https://github.com/mozilla/addons-server/issues/14020) has landed, I plan on working on this issue to make use of the new params. You seemed concerned in your comments that maybe we shouldn't be working on this at all, and instead focussing on solving the perf issues inside of code manager.

I think it's perfectly fine to work on this issue. I like the approach you took in [mozilla/addons-server#14020](https://github.com/mozilla/addons-server/issues/14020) and I believe it should result in a small patch for code-manager, so let's make good use of the API improvement!

> I agree that that should be a priority after this. You indicated that you did some experimentation with react-window, and I recall that @mirefly also said he'd done some work. There's also the idea of using inifinte scroll instead. Do you want to set up a brief meeting to discuss these, let me know where your work stands, and come up with a path to move forward with this?

Right. I think it would make sense to work on this after this issue. I don't really have a plan for that, though. As you mentioned, I only played with `react-window`, which is nice but there are some open-ended questions. The infinite scroll seems interesting too but it has problems too.

A meeting is a good idea but maybe you would like to investigate `react-window` and infinite scroll a bit so that we end up with a solid plan after the meeting? I can probably share my PoC by the end of this week.

**Comment by ioanarusiczki** [comment]
@bobsilverberg the `file_only`parameter is present in the API responses https://github.com/mozilla/addons-code-manager/issues/1599#issuecomment-657524273
Marking this verified on dev - FF78(Win10).
