### ISSUE TITLE
json files in compare view have different syntax highlighting

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1593]
Followup for https://github.com/mozilla/addons-server/issues/14132

An odd situation is that for the same addon but different locales the message.json file which contains 156 code lines has both:

the en_GB and en_US are highlighted 

https://code.addons-dev.allizom.org/en-US/compare/619691/versions/1691091...1691271/?allowSlowPages=true&path=_locales%2Fen_GB%2Fmessages.json

then the rest of the locales are not highlighted

https://code.addons-dev.allizom.org/en-US/compare/619691/versions/1691091...1691271/?allowSlowPages=true&path=_locales%2Fbe%2Fmessages.json

Notes:
As a general rule I've noticed that the .css, .html, .js and .json files display the highlighting disabled at 3000+ lines.

**Comment by bobsilverberg** [comment]
Thanks for filing the issue @ioanarusiczki. The rule for disabling highlighting on the compare page is this:

Highlighting will be disabled if either:
1. The total number of lines is >= 3000, or
2. The length of any single line is > 500

I checked `en-GB` and it does not have any lines longer than 500, but `be`, for example, has a line that is 537 characters long.

So I believe that this is the expected behaviour. We created that rule because we found performance was degraded both when a file is too long, but also when it's too wide. We might be able to increase that number from 500, but if this is only an issue (mostly) for locale files, then I think it's fine for those to not be highlighted.

@wagnerand What do you think?

**Comment by wagnerand** [comment]
If this affects locale files only, we can ignore it for now.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Then I believe that the files below should be highlighted since they have less than 500 chars. 

Let me know if I must file an issue.

Example of single lines with less than 500 chars that are not being highlighted in Compare view:

https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fbackground%2Findex.html - 149 chars
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fbackground%2Findex.html - 167 chars
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fconfirm%2Fframe.css - 324 chars
https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2F123rf.js - 252 chars
https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Fcontent%2Fengines%2Fdreamstime.js -
226 chars

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I found the problem. The logic added in https://github.com/mozilla/addons-code-manager/commit/d996749d6b90fbff16f0dd33d79695ca149960bd, to address https://github.com/mozilla/addons-code-manager/pull/1568#issuecomment-621867212 is faulty and is causing some files to "think" they haven't been highlighted. I'll look into a fix.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'm glad it's clarified!

**Comment by bobsilverberg** [comment]
@willdurand I'm having trouble creating a test that replicates the behaviour of a failed `tokenize`. The code I wrote for https://github.com/mozilla/addons-code-manager/commit/d996749d6b90fbff16f0dd33d79695ca149960bd was flawed, and I was able to find the bug, and write a test to prove that that bug was fixed, but now the test that proves that we catch a condition when `tokenize` fails is broken because I cannot seem to get `tokenize` to produce the `{ new: [[]], old: [[]] }` output in a test. I've tried all kinds of combinations of invalid JS, and I even tried copying the content of an example that was failing on dev, but that still doesn't work. Perhaps I'll put up a PR and you can take a look and see if there's something obvious I'm missing.

**Comment by bobsilverberg** [comment]
> @willdurand I'm having trouble creating a test that replicates the behaviour of a failed `tokenize`. The code I wrote for [d996749](https://github.com/mozilla/addons-code-manager/commit/d996749d6b90fbff16f0dd33d79695ca149960bd) was flawed, and I was able to find the bug, and write a test to prove that that bug was fixed, but now the test that proves that we catch a condition when `tokenize` fails is broken because I cannot seem to get `tokenize` to produce the `{ new: [[]], old: [[]] }` output in a test. I've tried all kinds of combinations of invalid JS, and I even tried copying the content of an example that was failing on dev, but that still doesn't work. Perhaps I'll put up a PR and you can take a look and see if there's something obvious I'm missing.

Of course, 5 minutes after posting that I figured it out. 😝

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF76(Win10). 
[This](https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?allowSlowPages=false&path=src%2Faction%2Findex.html) is a file with one code line with a length of 501 chars - highlighting is disabled.

![fixedcode](https://user-images.githubusercontent.com/33448286/83056919-db9b9d00-a05e-11ea-99b0-8631af1480d5.png)
