### ISSUE TITLE
Link to reviewer tools is .../null for a deleted add-on

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#1656]
### Describe the problem and steps to reproduce it:

If the add-on is deleted, the link to the reviewer tools in the top left corner is: https://reviewers.addons.mozilla.org/reviewers/review/null

### What happened?

Link is https://reviewers.addons.mozilla.org/reviewers/review/null

### What did you expect to happen?

Link should be `https://reviewers.addons.mozilla.org/reviewers/review/<addon-id>`
(Note that we can't use slug here since deleted add-ons don't have a slug (that's why we link to .../null)

**Comment by bobsilverberg** [comment]
In this issue you say the link should be to `reviewers.addons.mozilla.org/reviewers/review`, not to `reviewers.addons.mozilla.org/reviewers/review/{addonId}/`, the latter of which I believe you're doing in your PR. If the latter is correct, the issue description should be adjusted. Have you tested to make sure that `reviewers.addons.mozilla.org/reviewers/review/{addonId}/` actually works?

**Comment by wagnerand** [comment]
Hah, that got actually swallowed by markdown. I'll reformat to work around it.

**Comment by ioanarusiczki** [comment]
@wagnerand I verified this on dev with FF78(Win10), results:
- when an add-on is deleted from dev hub, I've noticed that the slug is automatically deleted from admin `models/addons/addon/<id>/change/`. This was the case when the issue was reproducible but now it's been fixed. Two examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/619911
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620007

- when an addon is deleted from `models/addons/addon/<id>/change/` the link will redirect to the rev tools page such as 
`https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/<slug>`  (as before so no issues here). 

- I found an edge case: when the add-on version is first deleted from dev hub and then the same add-on is entirely deleted (with the red `Deleted` button), then the rev tools page is no longer available using `id` or `slug`. I can view it using the `guid` but in this case from code-manager I am not redirected to the [rev tools page](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/adblock-plus-free-linter-test/), it's a 404. 

Examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/adblock-plus-free-linter-test/
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/619963/
or
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/00b1d1d1d6564570b229/
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/620005/

In case it should be filed let me know.

**Comment by ioanarusiczki** [comment]
Also for unlisted add-ons there's a redirect issue which was filed a while ago https://github.com/mozilla/addons-code-manager/issues/1538

**Comment by wagnerand** [comment]
Thanks! We don't delete add-ons from the django admin pages, so if I understand your test results correctly, everything should work as expected.

**Comment by ioanarusiczki** [comment]
@wagnerand Ok, then this issue is verified on dev - FF78(Win10).
