### ISSUE TITLE
Support shorthand URLs and guid/slugs

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#1685]
It would be great if the code manager made some assumptions on what to load based on the URL passed. This would allow me to use bookmarks or manipulate the URL to quickly load the addons I want to see:

`https://code.addons.mozilla.org/browse/123123123/`
should directly load the latest version of that add-on, redirecting to the version url.

`https://code.addons.mozilla.org/browse/id_or_guid_or_slug/`
passing guid (or slug) instead of add-on id would be great, just like in the reviewer tools.

**Comment by bobsilverberg** [comment]
Thanks for the suggestion @kewisch. These do sound like useful additions. Here are some comments on implementation:

> 
> `https://code.addons.mozilla.org/browse/123123123/`
> should directly load the latest version of that add-on, redirecting to the version url.
>

The current API requires that a version id be passed, so it seems that two options here are:
1. Update the API to accept only an add-on id and return the data for the most recent version.
2. Perform an initial API call via the front-end to get a list of versions for the add-on, and then issue a subsequent request to get the data for the most recent version.

The latter is more time and resource intensive, so the former is probably a better solution, but it would require work on the API. 

> `https://code.addons.mozilla.org/browse/id_or_guid_or_slug/`
> passing guid (or slug) instead of add-on id would be great, just like in the reviewer tools.

The API does not currently support passing a guid or a slug, it only supports the add-in id. In order to support this feature we would need to update the API to accept a guid, slug or id.

@wagnerand Can you comment on how you might prioritize these features?

**Comment by wagnerand** [comment]
I agree these sound useful. It's probably worth splitting this issue into two. I'll mark this one as a P3. The other should probably get the same. If we have time to mentor them, we could also nominate them for gfb.

**Comment by bobsilverberg** [comment]
These don't sound like candidates for gfb to me. Neither are small, simple things to do.

**Comment by wagnerand** [comment]
Alright then. I implemented an addons-frontend feature to access a listing by its guid and it was quite simple, so I thought this might be as well.
