### ISSUE TITLE
Handle API errors in App, Browse, and Compare components

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#182]
We did not really handle API errors so far, mostly because we don't have an error layer for that. Let's discuss this layer here.

- Do we want to introduce a layer similar to the error handler code in addons-frontend?
- Do we want to do something else? If so, what?

**Comment by bobsilverberg** [comment]
I do think we want something, but I think we should keep it as simple as possible for now. I don't have an immediate suggestion, other than that.

**Comment by EnTeQuAk** [comment]
As part of this discussion, I'm thinking about adding on-demand extraction for files that may have failed extraction during upload (for some reason, or these are legacy / unlisted add-ons or Mozilla signed add-ons). And in addition to that, I'll double-review possible errors that I'll try to forward as detailed as possible to the API so that reviewers get properly notified.

We should handle errors, luckily we can include much internal information to give reviewers a better sense of what failed given the importance of review errors should be clear and informative and ideally actionable.

**Comment by willdurand** [comment]
This has been partially fixed in #181.
