### ISSUE TITLE
Error when trying to access file

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#1836]
Accessing https://code.addons.mozilla.org/en-US/browse/2671857/versions/5131155/?path=background.js throws:

```
TypeError: e is null

    in NavbarBase
    in Connect(NavbarBase)
    in header
    in Header
    in div
    in FullscreenGridBase
    in Connect(FullscreenGridBase)
    in AppBase
    in Connect(AppBase)
    in Route
    in withRouter(Connect(AppBase))
    in Router
    in ConnectedRouter
    in Connect(ConnectedRouter)
    in Provider
    in ErrorBoundaryBase
```

https://sentry.prod.mozaws.net/operations/addons-code-manager-prod/issues/10431731/?environment=production

**Comment by bobsilverberg** [comment]
I can see what's happening here. In the API response `addon.name` is `null`, which is unexpected. Looking at how the types are defined in the app, we don't allow for `addon.name` to be `null`. Looking at the docs for the add-on detail API, it does say that `addon.name` can be null, but I'm not sure if that follows through for an add-on that is returned by the reviewers API. 

@eviljeff might you be able to check and see if the reviewers API is meant to be able to return a `null` for `addon.name`?

@wagnerand Can you think of a reason why this particular version would have an add-on with a null name?

If it's true that the API can return a null I'll need to update the code to allow for that.

**Comment by eviljeff** [comment]
> @eviljeff might you be able to check and see if the reviewers API is meant to be able to return a `null` for `addon.name`?

All translated fields _can_ return null if there's no translation in the `default_locale` for that field.  Looks like, from redash, this addon doesn't have a name in it's `default_locale` (`pl`) - it's an empty string which we drop along the way as invalid.  We should have prevented that add-on from being submitted without a name (because it a required field), so there's bug somewhere in the name extraction, or the linter, or the devhub/api submission validation.

**Comment by wagnerand** [comment]
> @wagnerand Can you think of a reason why this particular version would have an add-on with a null name?

There really shouldn't be a legitimate reason for an add-on to have a `null` name, or even a white-space-only name (which I've also seen recently).

**Comment by bobsilverberg** [comment]
Thanks for the feedback @eviljeff and @wagnerand. Based on the above, do you think I should change the code manager code to be able to deal with a `null` name, or is the consensus that this shouldn't be happening? Is it possible in this case (and any others found along the way) to update the data for the add-on so the name is not blank/null?

**Comment by willdurand** [comment]
> Thanks for the feedback @eviljeff and @wagnerand. Based on the above, do you think I should change the code manager code to be able to deal with a `null` name, or is the consensus that this shouldn't be happening? Is it possible in this case (and any others found along the way) to update the data for the add-on so the name is not blank/null?

My 2cents: I think we should put a default value in case the `name` is null or blank, e.g., `(none)` or something. I know it shouldn't happen, etc. but currently it breaks code-manager. I think this tool should be able to handle errors like this and not break, it's an important tool.

**Comment by eviljeff** [comment]
imo, with tools like the code-manager, and the reviewer/admin tools in general, they need to be super tolerant to bad data like things being missing when they really shouldn't be missing.

We could (probably should) fix the addon but something similar is quite likely to happen again because the codebase is old and sprawling (and, ultimately, because we can't enforce translations existing at the database level).

**Comment by bobsilverberg** [comment]
Fair enough. I'll fix it in code manager.

**Comment by wagnerand** [comment]
I agree, we should probably prevent this for future submissions, e.g. denying null/empty names.
But we also need the code-manager to be able to handle already existing submissions, which we cannot change unfortunately.

Thank you @bobsilverberg for handling this!

**Comment by AlexandraMoga** [comment]
I've verified the issue on -dev with different scenarios for both listed and unlisted add-ons:
- add-on name is empty in all supported locales
- add-on name set for the `default_locale` but empty in all other supported locales
- add-on name set for one of the supported locales but empty in the `default_locale` and remaining locales
- navigate the browse and compare pages, open and download files, etc

I've been using the add-on admin page to verify these scenarios because I could not find a way to create a listed add-on with an empty name (at some point you will hit the Name validation error thrown by the add-on submission form). I was able to create a pure unlisted add-on with an empty name though, so it would be good to know if the example seen on prod was a listed or an unlisted submission.

Examples:
Browse: https://code.addons-dev.allizom.org/en-US/browse/620401/versions/1692491/
Compare: https://code.addons-dev.allizom.org/en-US/compare/620401/versions/1692490...1692491/

![image](https://user-images.githubusercontent.com/31961530/107510426-98616a00-6bac-11eb-9dee-5321c4fcd960.png)
