### ISSUE TITLE
Connect the `FileTree` component?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#185]
The `FileTree` component uses https://github.com/gnapse/react-treefold in an uncontrolled way under the hood. I have the feeling that we could connect the tree by using the "controlled way".

I am wondering if we really want to do that though. "Connecting the tree" means putting the file tree into Redux and recording all the clicks on each node, i.e. all the state updates (opening a directory, clicking a file, etc.)

**Comment by bobsilverberg** [comment]
While I do think we should store as much as possible in the redux store, I don't think storing the state of the tree (in terms of what's collapsed and what's expanded) is going to buy us much, if anything. It just seems like it will result in a lot of unnecessary dispatches.

**Comment by kumar303** [comment]
Yes, we should definitely control as much of the app as possible with Redux. Something like file navigation is absolutely crucial to control with Redux. If we don't, we lose the ability to replay state from actions.

Additionally, Redux is the one true flow of data and when we violate that principle, subtle bugs creep into the app. See the [`<LinterProvider>` change](https://github.com/mozilla/addons-code-manager/pull/455#discussion_r268870489) as an example. In this case, the `FileTreeNode` component ceases to re-render because Redux is not in control of the flow of state changes. We have a hack in place that forces a re-render all the time but this may lead to performance problems at some point.

**Comment by bobsilverberg** [comment]
One of the features needed for keyboard shortcuts (#199) is the ability to expand the entire tree (and, I would think, collapse it as well). Looking at the code for `react-treefold`, it looks like it might make sense to convert our tree to controlled version prior to attempting to write code that will do the expand/collapse.

@willdurand | @kumar303 Do you agree?

**Comment by bobsilverberg** [comment]
Another feature required by shortcuts is the ability to select the next and previous files in the tree, and I believe that connecting the tree will also make this simpler.

**Comment by kumar303** [comment]
Yeah, it sounds like that's a good reason to connect expansion to Redux

**Comment by bobsilverberg** [comment]
Ok, I'm going to take this one on. I've started looking at how to make `react-treefold` controlled. It looks like we'll need to store all of the nodes of the tree in the redux store along with their expanded state. Then, when a user clicks on a node we would dispatch an action which updates the state, and that in turn would cause the FileTree to be updated accordingly.

Do we think we need to store a separate tree for each version, or will there always just be one active tree, and therefore we can just store one tree (i.e., the active one)?

**Comment by willdurand** [comment]
I had this patch a while ago: https://github.com/mozilla/addons-code-manager/pull/234

It was used to put some control on the `FileTree` (and automatically expanding the root node).
