### ISSUE TITLE
Config: should we use `.env` (dotenv, built-in with CRA)?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#3]
Instead of the [heavy configuration used in addons-frontend](https://github.com/lorenwest/node-config), we could maybe switch to something simpler, more intuitive and more cross-language: **dotenv**.

See: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#what-other-env-files-can-be-used

**Comment by kumar303** [comment]
Hmm, it's nice that CRA recommends this but I am confused. The [FAQ](https://github.com/motdotla/dotenv#faq) says that it should not be used the way CRA recommends 😮 

In general, I like how `.env.local` doesn't leak into tests (we have this problem with `config`). I dislike how files start with a dot. I would prefer to write config variables in JS because we can do things like import shared definitions.

**Comment by willdurand** [comment]
Answer: YES, we do use `.env` files.
