### ISSUE TITLE
View linter messages in the compare view for versions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#314]
User story:

> As a code reviewer, I want to see linter messages shown in the version compare view to speed up the review process.

This will be similar to showing linter messages in the file viewer: https://github.com/mozilla/addons-code-manager/issues/41

Example from the current site:

<img width="1197" alt="screen shot 2019-03-04 at 3 00 03 pm" src="https://user-images.githubusercontent.com/55398/53762706-63abea80-3e8e-11e9-8ca7-8c6759dca071.png">

**Comment by kumar303** [comment]
We will need a way to link into the `validation.json` URL: https://github.com/mozilla/addons-server/issues/10323#issuecomment-469415559

**Comment by kumar303** [comment]
Linter messages returned by the API will be only for the current version

**Comment by kumar303** [comment]
The linter messages shown will be for the newer version in the compare view

**Comment by willdurand** [comment]
In the `DiffView` component, one can show inlined content using `getWidgets()`:

```diff
+  getWidgets = (hunks) => {
+    return (
+      this.state.changesWithComments
+        .reduce((widgets, change) => {
+          const changeKey = getChangeKey(change);
+
+          return {
+            ...widgets,
+            [changeKey]: (
+              <Comment
+                comment={
+                  change.lineNumber === 39
+                    ? null
+                    : { content: 'This is not needed.' }
+                }
+              />
+            ),
+          };
+        }, {})
+    );
+  };
```

It also needs `widgets={this.getWidgets(hunks)}` to each `Diff` in `render()`.

The diff above ha a list of comments stored in `this.state.changesWithComments` because a button was also added to add new comments. For linter results, we won't need the `state`, but it shows how to create a list of widgets. The `lineNumber` can be found via `change.lineNumber` but it could also be `change.oldLineNumber` or `change.newLineNumber`.

**Comment by kumar303** [comment]
I think we added `needs: api` because we wanted the results included in the main API response (https://github.com/mozilla/addons-server/issues/10620) but we have a workaround in place.
