### ISSUE TITLE
Deploy dev

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#327]
Deploy the app to dev as a step towards full deployment: https://github.com/mozilla/addons-code-manager/issues/25

The domain will probably be `code.addons-dev.allizom.org`

Notes:
- We have a build step that creates a static HTML site
- There is also a Node.js server that needs to handle all incoming requests

See [`yarn build`](https://github.com/mozilla/addons-code-manager#yarn-build) and `yarn start` (not documented for some reason).

**Comment by willdurand** [comment]
The sooner, the better! Do we need ops?

**Comment by willdurand** [comment]
I started the docker integration: https://github.com/mozilla/addons-code-manager/pull/343

>  `yarn start` (not documented for some reason).

yeah, I think we should remove this command as it is not used (or we alias it to another more useful command)

**Comment by willdurand** [comment]
@bqbn and @autrilla: we'd like to create a hosted -dev env (the sooner, the better). A few things:

- this project already contains a `Dockerfile` but there is no `version.json` yet
- we have at least two environment variables to give to the running docker containers:
  - `REACT_APP_API_HOST` with `https://addons-dev.allizom.org` as value
  - `REACT_APP_SENTRY_DSN` with a public Sentry DSN (project has to be created in Sentry)

**Comment by bqbn** [comment]
@willdurand, what do you mean by "a hosted -dev env"? 

Do you need the full stack? i.e. the frontend, the backends, the database, the elasticsearch cluster, redis and etc., or do you just need a separate frontend stack? And how would you like push to the said environment? and etc.

We need more info and background in order to know what ops need to do.

Because this sounds like a lot for ops to set up, and is also under such a short notice, we cannot commit to a timeline when we can set this up, at this point.

**Comment by willdurand** [comment]
> @willdurand, what do you mean by "a hosted -dev env"?

Sorry, we want this project to be deployed and available at: `code.addons-dev.allizom.org`
 
> Do you need the full stack? i.e. the frontend, the backends, the database, the elasticsearch cluster, redis and etc., or do you just need a separate frontend stack? And how would you like push to the said environment? and etc.

It is a new frontend application that talks to the addons-server API, so we only need a separate "frontend stack" I believe.

We would like to have each commit to `master` deployed (like on addons-frontend for the -dev env).

> We need more info and background in order to know what ops need to do.
> 
> Because this sounds like a lot for ops to set up, and is also under such a short notice, we cannot commit to a timeline when we can set this up, at this point.

No problem, let us know which information you need and how we can help you :)

**Comment by bqbn** [comment]
OK, this sounds like it can take 1.5 to 2 weeks of time with everything else that happens at the same time. I can start this early next week.

**Comment by bqbn** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1534464 for it.

**Comment by willdurand** [comment]
> Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1534464 for it.

@bqbn thanks, for some reasons, I am not able to see it though (not authorized)

**Comment by bqbn** [comment]
@willdurand wrong permission set for the bug. Please try again.

**Comment by bqbn** [comment]
Regarding the notes above,

> We have a build step that creates a static HTML site

Does the created static HTML site need to be deployed? Is it correct that `code.addons-dev.allizom.org` should be the static HTML site?


> There is also a Node.js server that needs to handle all incoming requests

Assuming `code.addons-dev.allizom.org` is hosting the above mentioned static HTML site, under which domain is the Node.js server hosted?

**Comment by willdurand** [comment]
> Does the created static HTML site need to be deployed? Is it correct that `code.addons-dev.allizom.org` should be the static HTML site?

It is already bundled into the Docker image, which contains the entire application.

To give a bit more context, it's not a 100% static site because we modify the compiled HTML to inject a token (that's why there is a node server). All the static files are served by the node server (Express app, using the [static middleware](https://expressjs.com/en/starter/static-files.html)).

Redirecting `code.addons-dev.allizom.org` to a container running the Docker image should be sufficient and everything should just work (assuming environment variables are set with the correct values).

Other information you might be interested in:

- there are no server logs and I don't think we'll ever have logs in the future, the server logic is very small (authentication by reading a cookie and injecting the token into the HTML response)
- JS and CSS filenames contain hashes and are referenced in the (unique) HTML file that is served by the node server. Cache is disabled for this HTML file because it might contain a user token and we ran into caching issues on addons-frontend (with a similar setup, i.e. user data sent into the HTML response). There are cache headers for the static files (with sensible values)

**Comment by kumar303** [comment]
> there are no server logs and I don't think we'll ever have logs in the future

Since we have custom server code, we will need server logs but it can be a lower priority change. If something goes wrong on the server (500 errors), we may want to look at logs.

**Comment by kumar303** [comment]
@moz-jvehent when this issue closes we will have the first publicly hosted version (just a dev version). See https://github.com/mozilla/addons-code-manager/issues/25 for stage and prod.

**Comment by willdurand** [comment]
@bqbn sorry I forgot some more information: just like addons-frontend, we want all API requests to go to addons-server directly (i.e. all requests starting with `/api/`).

I thought we did not want a CDN yet, which is partially wrong. We won't have a lot of users so performance is not relevant here, but we would like to have two separate domains for CSP purpose.

This does not have to be two instances though. For example, we could configure two domains at the nginx level, pointing to the same Docker container:

- `code.addons-dev.allizom.org` would send all requests but `/static/` to the container
- `code.addons-amo-dev-cdn.allizom.org` would send the `/static/` requests to the container too

**Comment by bqbn** [comment]
> I thought we did not want a CDN yet, which is partially wrong. We won't have a lot of users so performance is not relevant here, but we would like to have two separate domains for CSP purpose.

That's fine. We'll have a Cloudfront distribution for this project anyways. We already have tooling and templates to create and manage CDN for the existing 2 addons frontends. Not using CDN actually makes this a special case for operating it, which I'd like to avoid.

The cdn domain names though, will be `addons-code-manager-dev-cdn.allizom.org`, `addons-code-manager-stage-cdn.allizom.org` and `addons-code-manager.cdn.mozilla.net` for -dev, -stage, and -prod env respectively (this is so that the naming is consistent with the cdn domain names used by other 2 existing frontends).

**Comment by willdurand** [comment]
Ok, perfect. Thank you!

**Comment by bqbn** [comment]
And a couple more questions if you don't mind:

1. How do we run the built image? Following the convention we had with addons-frontend, I tried to run it with `docker run mozilla/addons-code-manager:latest /bin/sh -c "yarn build && yarn start"` and it doesn't seem to work.

    The error info is,

    ```
    Mar 20 00:59:33 ip-172-31-43-28.ec2.internal systemd[1]: Started Daemon for addons-frontend.
    Mar 20 00:59:34 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: yarn run v1.13.0
    Mar 20 00:59:35 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: $ react-scripts build
    Mar 20 00:59:37 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: Could not find a required file.
    Mar 20 00:59:37 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: Name: index.html
    Mar 20 00:59:37 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: Searched in: /app/public
    Mar 20 00:59:37 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: error Command failed with exit code 1.
    Mar 20 00:59:37 ip-172-31-43-28.ec2.internal docker-addons-frontend[14746]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    ```

    It looks like it is the `yarn build` command that failed.

2. Second question is, I seem to remember the reason we run `yarn build` for addons-frontend is so that it generates static files with unique names every time. If we don't need to run `yarn build` for this app, are static file names a concern? (Note that the static files are uploaded to an S3 bucket, and served by cloudfront)

**Comment by willdurand** [comment]
>     1. How do we run the built image? Following the convention we had with addons-frontend, I tried to run it with `docker run mozilla/addons-code-manager:latest /bin/sh -c "yarn build && yarn start"` and it doesn't seem to work.

There is no need to override the default command, it can be run as a regular docker image:

```
docker run mozilla/addons-code-manager:latest
```


>     2\. Second question is, I seem to remember the reason we run `yarn build` for addons-frontend is so that it generates static files with unique names every time. If we don't need to run `yarn build` for this app, are static file names a concern? 

Static files will get unique names every time too. The difference is that assets are compiled during the docker image build.

> (Note that the static files are uploaded to an S3 bucket, and served by cloudfront)

So, you need to access the static files during the deployment in order to upload them to S3, right? I thought we could skip that given that we don't need the perf benefits of a CDN but I guess it is the way apps are deployed.

How do you plan to upload the static files? How do you actually get the files for `addons-frontend`?

For addons-code-manager, you could retrieve them from the Docker image:

```
CID=$(docker create mozilla/addons-code-manager:latest)
docker cp ${CID}:/app/build/static . # This creates a `static/` directory in the current working directory
docker rm ${CID}
```

We want the entire `static` folder to be uploaded.

---

@kumar:

That being said, using this CDN won't be straightforward in our app (because of CRA) 🤔 The CDN URL needs to be set at build time and we do not have any environment-specific configuration at build time (i.e. variables that are different for prod, stage, dev). This means our nice Docker images (that are environment-agnostic) cannot be used.

Therefore, I see two options:

1. we change how the `Dockerfile` is built. We could simply add the source code and install the node dependencies. Building the app would happen during the deployment as we need "buildtime variables" (`PUBLIC_URL`) and not only "runtime vars".
2. we rewrite the `\/static\/` paths in the `index.html` response served by the node server. We already modify the response to inject the token, so 🤷‍♂️ This option has the advantage to keep the current `Dockerfile` and get rid of the required "buildtime variable". We could introduce a `CDN_URL` variable in our `.env*` files and `.env.common-local` would unset this variable.

Option (2) would allow to keep the nice Docker image we currently build. For instance, I can apply the following change in the `docker-compose.dev.yml` file:

```diff
diff --git a/docker-compose.dev.yml b/docker-compose.dev.yml
index bd6c084..2479fb7 100644
--- a/docker-compose.dev.yml
+++ b/docker-compose.dev.yml
@@ -1,7 +1,8 @@
 version: '3'
 services:
   web:
-    build: .
+    # build: .
+    image: mozilla/addons-code-manager:latest
     env_file:
       - .env.dev
       - .env.common-local
```

Running `docker-compose up` will run a container for this image locally and everything will just work. This is great because the images built _via_ Docker Hub are exactly the ones that will be deployed by ops. The exact same code would run in different environments (thanks to the runtime environment variables).

If we go for (1), then we won't be able to pull a docker image from the Hub and run the app directly. One will have to run `yarn build`, etc. That sounds less nice but there is no need to change the `index.html` in the server code.

**Comment by bqbn** [comment]
@willdurand  the CDN URL can be passed to the application at run time, as an environment variable. I'm not sure if that solves any problem or not, but just calling it out.

As regarding,

> How do you plan to upload the static files? How do you actually get the files for `addons-frontend`?

For `addons-frontend` the static files are built at run time, so we start a container, wait for it to finish building, copy the static files out, then upload them to S3. Pretty similar as you showed above.

**Comment by willdurand** [comment]
> @willdurand the CDN URL can be passed to the application at run time, as an environment variable. I'm not sure if that solves any problem or not, but just calling it out.

Unfortunately, we need this variable at build time 😢 

> For `addons-frontend` the static files are built at run time, so we start a container, wait for it to finish building, copy the static files out, then upload them to S3. Pretty similar as you showed above.

Oki, thanks.

**Comment by willdurand** [comment]
A more future-proof solution would be to have the node server renders the HTML that currently lives in `index.html` so that we have full control over it (no more update on-the-fly). We could rely on the `build/assets-manifest.json` file to know which static files have been generated by CRA.

**Comment by bqbn** [comment]
Dev site is up and here: https://code.addons-dev.allizom.org/

Please file issues for -stage and -prod as you see fit. Please let us know the timeline for bring them up in the issues.

**Comment by willdurand** [comment]
Thanks @bqbn, I filed:

- #460: we need to change some of our code to use the correct API host
- #462: we need to fix the login button (similar to #460)
- #463: we need new FxA configurations in -dev, stage and prod. We cannot reuse the configs named `amo`

**Comment by willdurand** [comment]
So, the introduction of the `REACT_APP_API_HOST` env var (#470) and the need for specifying the API host when calling the API (#460) made me realize that this could not work.

I totally forgot that `process.env.XYZ` variables would be stripped at build time. This works well when using the insecure proxy because this proxy runs on the server, which can handle `process.env.XYZ` variables at runtime but most of our code is compiled.

It looks like we need to:

1. update the `Dockerfile` to not compile the files, it should simply copy the files of the project and install the node dependencies, including the dev deps
2. the default `Dockerfile` command should be `yarn build && yarn serve`
3. remove the `docker-compose.dev.yml` file (this file won't be super useful anymore)

**Comment by willdurand** [comment]
> So, the introduction of the `REACT_APP_API_HOST` env var (#470) and the need for specifying the API host when calling the API (#460) made me realize that this could not work.
> 
> I totally forgot that `process.env.XYZ` variables would be stripped at build time. This works well when using the insecure proxy because this proxy runs on the server, which can handle `process.env.XYZ` variables at runtime but most of our code is compiled.
> 
> It looks like we need to:
> 
>     1. update the `Dockerfile` to not compile the files, it should simply copy the files of the project and install the node dependencies, including the dev deps
> 
>     2. the default `Dockerfile` command should be `yarn build && yarn serve`
> 
>     3. remove the `docker-compose.dev.yml` file (this file won't be super useful anymore)

So, this worked. Problem solved.

**Comment by willdurand** [comment]
I am closing this issue now since most features work in -dev. Thanks!
