### ISSUE TITLE
ESLint reporter tries to run ESLint on non-existent files, sometimes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#396]
There seems to be an issue with the ESLint reporter. I am not exactly sure what it is but, sometimes, the ESLint reporter outputs an error in the test suite about a file that does not exist. It is probably related to the `git status` parsing.

I filed this issue after @muffinresearch mentioned it to me today. I encountered the problem too, so next time I get this error, I'll fix it :)

**Comment by muffinresearch** [comment]
The way I came across this, was by adding a new type definition in `src/@types` without committing (or staging it).  

The message was something like `Error: No files matching 'src/@types/[file]' ...`

It was only after committing this that the error went away. I'm not sure if staging it is enough, but if the message at least pointed to the solution it would have saved a bit of time, since I assumed that something was wrong with how the type definition was setup even though `tsc` was happy.

In the end I gave up trying to figure it out and worked on the tests by running them standalone. It was only then when I'd got to a point where I made the commit that suddenly the error was gone!
