### ISSUE TITLE
Create a KeyboardShortcuts component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#459]
This supports #199.

As a starting point, create a component that renders a list of keyboard shortcuts and dispatches events when those keys are pressed. Follow-ups will be filed to respond to those events.

**Comment by willdurand** [comment]
@ioanarusiczki added QA instructions

**Comment by AlexandraMoga** [comment]
Navigating the file tree by keyboard is working both in the browse and compare page and a widget displaying the supported shortcut keys is also present in the left side panel.

![2019-04-17_15-15-35](https://user-images.githubusercontent.com/31961530/56287776-ea0e4a00-6125-11e9-9ccf-f6b0f53add34.gif)

![image](https://user-images.githubusercontent.com/31961530/56287863-25a91400-6126-11e9-92b6-648f5be15a6a.png)


There is one misbehavior in the compare view, where the previously selected folder will be closed automatically when the next folder is opened, but I believe this has the same root cause as #592
