### ISSUE TITLE
Document how to run the app in production

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#467]
Document how to run the production app (the `yarn start` command).

For local development, add a note saying one should run `rm .env.local` first.

See https://github.com/mozilla/addons-code-manager/issues/327

**Comment by willdurand** [comment]
`yarn start` is not used in the `Dockerfile` or during the deployment.

I wanted to get rid of this script because it is confusing. It does 2 things (build + run) and there is no notion of an environment. It always reads `.env` (and `.env.local` if it exists). This command cannot really be used for a real life scenario, so I'd like to:

1. remove the command
2. document how we can run the app like in production, either using the `Dockerfile`, or the Docker image available on the Docker Hub, or locally with `yarn build` and `yarn serve`

WDYT?

**Comment by willdurand** [comment]
I think we could also document the `.env` config with the different files and how it works.
