### ISSUE TITLE
FontAwesomeIcon makes navigation slow

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#504]
From profiling data, it seems like `<FontAwesomeIcon />` (maybe?) causes a lot of slowness while expanding / collapsing folders (https://github.com/mozilla/addons-code-manager/issues/494). I'm not sure why exactly but addressing this seems like it could have a big effect on speed. Here it is shown as the slowest part of `FileNodeTree`:

<img width="555" alt="Screenshot 2019-03-29 14 35 26" src="https://user-images.githubusercontent.com/55398/55258415-c9db2180-5230-11e9-95af-c804ee07271e.png">

Here is a rough average of the time it takes to expand / collapse a folder (with CPU throttling), a sample grabbed using https://github.com/mozilla/addons-code-manager/pull/501

<img width="1063" alt="Screenshot 2019-03-29 14 36 43" src="https://user-images.githubusercontent.com/55398/55258432-d19ac600-5230-11e9-9760-e12800e5f6a1.png">

With a patch that turns `<FontAwesomeIcon >` into a no-op, here is another average sample of expanding / collapsing folders:

<details>
<summary>patch</summary>

```diff
diff --git a/src/components/FileTreeNode/index.tsx b/src/components/FileTreeNode/index.tsx
index 681ba4e..71220b1 100644
--- a/src/components/FileTreeNode/index.tsx
+++ b/src/components/FileTreeNode/index.tsx
@@ -1,8 +1,8 @@
 import * as React from 'react';
 import { ListGroup } from 'react-bootstrap';
-import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
 import makeClassName from 'classnames';
 
+import Icon from '../Icon';
 import { gettext } from '../../utils';
 import { TreefoldRenderPropsForFileTree } from '../FileTree';
 import LinterProvider, { LinterProviderInfo } from '../LinterProvider';
@@ -139,7 +139,7 @@ class FileTreeNodeBase<TreeNodeType> extends React.Component<PublicProps> {
 
       nodeIcons = (
         <span className={styles.nodeIcons}>
-          <FontAwesomeIcon icon={getIconForType(linterType)} title={title} />
+          <Icon icon={getIconForType(linterType)} title={title} />
         </span>
       );
     }
@@ -171,9 +171,9 @@ class FileTreeNodeBase<TreeNodeType> extends React.Component<PublicProps> {
             style={{ paddingLeft: `${level * 12}px` }}
           >
             {isFolder ? (
-              <FontAwesomeIcon icon={isExpanded ? 'folder-open' : 'folder'} />
+              <Icon icon={isExpanded ? 'folder-open' : 'folder'} />
             ) : (
-              <FontAwesomeIcon icon="file" />
+              <Icon icon="file" />
             )}
             <span className={styles.nodeName}>{node.name}</span>
             {nodeIcons}
diff --git a/src/components/Icon/index.tsx b/src/components/Icon/index.tsx
new file mode 100644
index 0000000..4b3c211
--- /dev/null
+++ b/src/components/Icon/index.tsx
@@ -0,0 +1,12 @@
+import * as React from 'react';
+import {
+  FontAwesomeIcon,
+  Props as FontAwesomeIconProps,
+} from '@fortawesome/react-fontawesome';
+
+const Icon = (props: FontAwesomeIconProps) => {
+  return <span>ico</span>;
+  // return <FontAwesomeIcon {...props} />;
+};
+
+export default Icon;
```

</details>

<img width="1018" alt="Screenshot 2019-03-29 14 38 34" src="https://user-images.githubusercontent.com/55398/55258497-fc851a00-5230-11e9-8de8-975e1a2aa16e.png">

**Comment by kumar303** [comment]
I should mention that I tried to add caching to this component but it didn't make a difference. `React.memo` doesn't help because a new component is created each time by treefold (nothing gets memo'd). When I hooked up [`moize`](https://planttheidea.github.io/moize/), I could verify that it was loading an instance from cache (skipping `render()`) but this didn't have an effect. It was still just as slow.

**Comment by willdurand** [comment]
- Could it be slow because of the SVG render?
- Could it be that the profiler report `FontAwesomeIcon` as the culprit but it is actually not it? I've seen that with profiles in other languages where the root cause was not the most obvious identified one.

**Comment by willdurand** [comment]
I did some Chrome profiling too.

> Here is a rough average of the time it takes to expand / collapse a folder (with CPU throttling), a sample grabbed using #501

It takes 34 to 50ms to open/close a folder with cpu throttling set to "6x slowdown".

> With a patch that turns `<FontAwesomeIcon >` into a no-op, here is another average sample of expanding / collapsing folders:

I am not sure this patch is unbiased because it returns a text node when the FA component is no-op'ed. We would need a `Icon` component that renders an icon, which means re-implementing the FA react package. Looking at the bottom of the inverted flamegraph, I don't see any issue with `FontAwesomeIcon`. It does not take a lot of time compared to the rest, but it is called N times because there are N `node` rendered. Each inverted spike in the screenshot below is a node (`FileTreeNodeBase`) that renders when we toggle a folder:

![Screen Shot 2019-04-01 at 11 53 33](https://user-images.githubusercontent.com/217628/55319272-c9cb6380-5474-11e9-9308-a57eb3611f42.png)

Zooming on one node gives this:

![Screen Shot 2019-04-01 at 11 55 06](https://user-images.githubusercontent.com/217628/55319375-05fec400-5475-11e9-8f88-e99a02a6c18a.png)

We can see that `FontAwesomeIcon` takes half the time of `ForwardRef` for its own code, which means the code executed in `ForwardRef` takes about the same time as the code executed by `FontAwesomeIcon`. That's why I believe `FontAwesomeIcon` is not the right target.

One explanation for the quick win introduced by the patch above is that rendering a text node is always faster than rendering a component, especially when we multiply this small gain by 37 or 38 (the number of spikes in the fist screenshot above).

I see similar results on each toggle action of the profile I recorded: toggling a folder implies 30+ `FileTreeNode` to be re-rendered. This does not make sense to me because it should be more like 3 to 6 `FileTreeNode` re-rendered and not more: the one that is toggled + its children.

That being said, because the tree recursively renders itself and, when a React component is rendered, all its children are automatically rendered by default, that might be why there are so many `FileTreeNode` re-renders.

Maybe implementing something like `shouldComponentUpdate()` or using `PureComponent` on the `FileTreeNode` would help.

**Comment by kumar303** [comment]
I reduced the priority on this issue because it's fast enough 😄 It's an interesting curiosity but not something worth spending time on right now.

> Maybe ... using `PureComponent` on the `FileTreeNode` would help.

I tried this but it didn't help. I think it's because `Treefold` constantly creates new `FileTreeNode` instances for some reason, as discussed in https://github.com/mozilla/addons-code-manager/issues/494#issuecomment-478646656

**Comment by kumar303** [comment]
The reason I was suspicious about `<FontAwesomeIcon>` is that it had a high self time which is a measure of the [actual time spent](https://stackoverflow.com/questions/7127671/difference-between-self-and-total-in-chrome-cpu-profile-of-js) in that component.

**Comment by kumar303** [comment]
It's not really worth keeping this issue open, even if there is something going on with this component. We have already addressed enough performance issues to make navigation fast for these pages.
