### ISSUE TITLE
Provide keyboard navigation for next / previous diff

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#615]
User story

> As a reviewer, I want to quickly navigate between the next / previous diff so I can focus on just the changes introduced by a new version.

Keyboard shortcuts:
* `n` for next diff
* `p` for previous diff

See https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/git-add-delete-example and https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare/376192...376191/ to view this in the old site.

<img width="175" alt="Screenshot 2019-04-18 10 31 03" src="https://user-images.githubusercontent.com/55398/56372915-8d626c00-61c5-11e9-9823-53bce184a15f.png">

**Comment by kumar303** [comment]
@bobsilverberg this is pretty high priority (higher than showing / hiding the files). We missed filing this originally, whoops.

**Comment by willdurand** [comment]
Note: in today's Show & Tell, we've been reminded about these shortcuts **and** this issue has a higher priority than other keyboard shortcuts (because reviewers heavily rely on these shortcuts).

**Comment by bobsilverberg** [comment]
I'm not trying to take anything away from the importance of this issue, but I just tried the shortcuts using the link above and they don't work. Neither `n` nor `p` take me to the next diff consistently. I recall that @wagnerand reported in another issue that many of the shortcuts no longer work as expected.

Aside from that, I'm not sure what the exact requirement is. What exactly do we mean by "next diff"? Is it just the next file in the tree, or is it the next difference in the current file?

@wagnerand @kumar303 @willdurand

**Comment by wagnerand** [comment]
It means next difference in current file. If there is none, then go to first diff in next file.

**Comment by bobsilverberg** [comment]
Thanks @wagnerand.

> It means next difference in current file. If there is none, then go to first diff in next file.

Do we consider a difference the very next line that represents a change, or the next set of lines that represent a change? For example, assuming the user has the following line highlighted, which is the first deletion in a block: https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/?path=META-INF%2Fmanifest.mf#D15, would we expect that pressing `n` would take them to https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/?path=META-INF%2Fmanifest.mf#D16 (i.e., the very next line, which is also a deletion), or to https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/?path=META-INF%2Fmanifest.mf#D55 (i.e., the beginning of the next set of changes)?

**Comment by bobsilverberg** [comment]
We discussed this on IRC and ultimately we'd like it to work so that pressing the key takes the user to the beginning of the next *block of changes*. We could, as a starting point, implement it so that pressing the key takes the user to the next changed line, but I'm not sure how much less work that would be, so it might make sense to just implement the "moving between blocks of changes" feature off the bat.

Looking at what we currently have, I'm trying to figure out how we would implement this. In terms of the diff data, all we currently have in state is a set of changes, each of type [`ChangeInfo`](https://github.com/mozilla/addons-code-manager/blob/479a276bcc91f4696b9928836e88b3210675c85c/src/%40types/react-diff-view/index.d.ts#L6-L15), which has properties for `isDelete`, `isInsert`, `isNormal`, `lineNumber`, `newLineNumber`, `oldLineNumber` and `type`, the first three of which (and the last of which) could be used to identify a line as a change. It looks like `lineNumber` can be used to determine the anchor for the line, where a deletion with `lineNumber` of 5 would have an anchor of `#D5`, and an insertion with `lineNumber` of 5 would have an anchor of `#I5`.

One difference between this feature and navigating between linter messages is that with linter messages we have access to all of the messages at any given time, via the LinterProvider, but we only have access to changes for the current file at any given time. This can be dealt with using the new `status` that is returned to us in `entries` for a version, although I just came across an odd edge case for that which could cause headaches.

So the approach I an envisioning is to look for the next block of changes in the current file (by having a function which can return a list of line id’s for the first line in each block), and if there are no more blocks of changes in the current file, then we go to the next file which does have a change. The problem is, we don’t know on which line the next block of changes is, until *after* we have loaded that file. So it seems like we’d have to load that file, and indicate that we need to go to the first set of changes after the file has been loaded (e.g., via a URL param). This feels clunky and complicated, but I’m not sure how else we could do it, other than getting back a full list of all changes for a version when we request the version info, because right now we only get the list of changes after requesting the diff.

@kumar303 @willdurand I'd like to hear your thoughts on the above. Is there a different approach that would be simpler? How bad is this seeming requirement to load a new file and *then* select the first set of changes in that file?

**Comment by kumar303** [comment]
Since we currently only get the list of changes after requesting a file diff, I suggest starting the feature by just navigating from one file diff to the next file diff. After getting that to work, try navigating between changes in each file.

**Comment by bobsilverberg** [comment]
> I suggest starting the feature by just navigating from one file diff to the next file diff.

Just to clarify, you mean navigating between diffs in a single file (for now)?

**Comment by kumar303** [comment]
Maybe I'm a little confused. I thought you were saying that knowing the file diffs is hard before you can load the file. All I'm suggesting is to maybe start with a smaller subset of the feature, one that's easier to accomplish in a short patch. You could build on top of it.

Maybe it would help to start with a quick draft PR, a proof of concept? It wouldn't have to be functional.

**Comment by bobsilverberg** [comment]
Thanks @kumar303. I am confused too. I wasn't sure whether you were suggesting that the initial small feature would:
- allow a user to navigate only between changes in the current file
or:
- allow a user to navigate only between files which have differences in them

I interpreted it as the former, which resulted in https://github.com/mozilla/addons-code-manager/pull/643

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, WIn10x64

- you can navigate with `n` and `p` between next and previous differences in the compare view (the option is deactivated in the browse page)
- when there are no more differences to highlight in the current file, the navigation jumps to the next/previous file that contains differences
- the other keyboard navigation options are still working

![image](https://user-images.githubusercontent.com/31961530/58618254-ce709480-82ca-11e9-84a1-85859d4cfee3.png)

![2019-05-30_10-45-16](https://user-images.githubusercontent.com/31961530/58618262-d29cb200-82ca-11e9-997a-70a846fb38ff.gif)
