### ISSUE TITLE
Deal with reloading a version in a more fine grained way

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#671]
**For QA**: check for regressions in https://github.com/mozilla/addons-code-manager/issues/592 and other features on the compare page.

This is a follow-up from #627. That implemented a short-term fix, but it prevents us from reloading a version when calling `fetchDiff()`. @kumar303 made a couple of suggestions of different ways of addressing this in the issue, which I will quote below:

From https://github.com/mozilla/addons-code-manager/pull/627#discussion_r279507738:

> This seems fine as a short term fix but it doesn't seem like the right thing to do. It's better than the last iteration but it still would never allow us to reload a version from the server when calling `fetchDiff()`. I suggest filing an issue to introduce another action, like `fetchDiffPath()`, which would only be for switching paths within the same version. That seems like a better way to fix it. 
>
> Alternatively, we could introduce a new action parameter like `loadVersion: boolean` to indicate whether a version should be loaded.

**Comment by kumar303** [comment]
A bug caused by the implementation: https://github.com/mozilla/addons-code-manager/issues/776

**Comment by kumar303** [comment]
> I suggest ... to introduce another action, like fetchDiffPath(), which would only be for switching paths within the same version. That seems like a better way to fix it.

This still seems better but I couldn't figure out a way to do it when working on https://github.com/mozilla/addons-code-manager/issues/776. It's tricky because the loading only occurs when the component mounts, after switching URLs. There is no direct correlation between selecting a file and initiating the loader.

It would still be nice to address this issue so that we can reload version objects from the server when they change and also to avoid more surprises in the future.
