### ISSUE TITLE
The file tree jumps to the the current selected file when a subfolder is opened

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#699]
**STR**

1. Open the browse files page for an addon - https://code.addons-dev.allizom.org/en-US/browse/616666/versions/1655561/
2. Locate a sub-folder in the file tree and click on it

**Actual result:**
The file viewer jumps back to the current open file

**Expected result:**
The file viewer remains in the position where the sub-folder was expanded

**Notes:**
- reproduced on -dev with Fx66, Win10x64
- I could not reproduce in the compare page

![2019-05-07_14-11-03](https://user-images.githubusercontent.com/31961530/57295514-623bb000-70d3-11e9-9167-f2a8e7424f46.gif)

**Comment by wagnerand** [comment]
This looks similar to #642.

**Comment by bobsilverberg** [comment]
This is likely due to https://github.com/mozilla/addons-code-manager/pull/687. I can take a look this morning.

**Comment by bobsilverberg** [comment]
Yes, this was definitely introduced by #687. The problem is that that patch causes the currently selected file to always scroll into view whenever the `FileTreeNode` component mounts or updates, and expanding a folder dispatches `TOGGLE_EXPANDED_PATH`, which seems to cause a number of mounts. This is coupled with the fact that `isSelected` on `FileTreeNode` only cares about which file is currently selected (via `version.selectedPath`), and is unaffected when a user selects a folder to expand. Thus far we have never really cared about when a user selected a folder to expand, and have only used that event to add to `expandedPaths`, but it looks like we now might need to change that, and have a way of knowing which is the currently selected folder.

@kumar303 what are you thoughts on this?

**Comment by kumar303** [comment]
> @kumar303 what are you thoughts on this?

It makes the site unusable so we should fix it ASAP 😀 I'll take a look.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

- there's no more scroll jumping in the file tree
![2019-05-17_17-11-35](https://user-images.githubusercontent.com/31961530/57934510-8e6fe180-78c8-11e9-9bbb-e6e439f0f71c.gif)
