### ISSUE TITLE
Show add-on name in top bar

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#756]
Instead of showing _addons-code-manager_, we could show the add-on name. Showing the version would also be nice, at least in browse mode. In compare mode, you can see the versions in the compare dropdowns.

**Comment by kumar303** [comment]
https://github.com/mozilla/addons-code-manager/pull/806 added a similar feature but for web browser page titles. Maybe we can re-use that functionality here.

**Comment by mirefly** [comment]
I found it more complicated than I expected... I need to access `versionId` from `Navbar`, so I put `Navbar` in `Route` like the following. I am not sure I am on the right track @kumar303 

```diff 
--- a/src/components/App/index.tsx
+++ b/src/components/App/index.tsx
@@ -157,10 +157,15 @@ export class AppBase extends React.Component<Props> {
 
     return (
       <FullscreenGrid>
-        <Header>
-          {!loading && <Navbar />}
-          {this.renderErrors()}
-        </Header>
+        <Route
+          path={'/:lang/browse/:addonId/versions/:versionId/'}
+          children={() => (
+            <Header>
+              {!loading && <Navbar />}
+              {this.renderErrors()}
+            </Header>
+          )}
+        />
         {this.renderContent()}
       </FullscreenGrid>
     );

```

**Comment by kumar303** [comment]
@mirefly yeah, this one is tricky. Using a route won't work for [compare views](https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/) since the URL parameters for fetching the version are different. I'm actually trying to come up with a solution for propagating the "current version" to the header in https://github.com/mozilla/addons-code-manager/issues/805 so maybe hold off on this issue for a week-ish?

You might find some interesting issues in the [code quality](https://github.com/mozilla/addons-code-manager/issues?q=is%3Aissue+is%3Aopen+label%3A%22component%3A+code+quality%22) label. However, some are more complex than others.

**Comment by wagnerand** [comment]
This is quite relevant since #789 is fixed.

**Comment by kumar303** [comment]
@mirefly did you want to take another look? It should be easier now that we have https://github.com/mozilla/addons-code-manager/pull/885 . 

Here is a commit that shows how to access the current version in `App`: https://github.com/mozilla/addons-code-manager/pull/892/commits/1c10355f6a61df84d038cef6dba57cb0f5d3c9db#diff-af52e1a50c2d496326d0d154cac3097dR202 However, that commit never landed because we decided not to implement the display of general linter messages in the `App` component.

**Comment by mirefly** [comment]
Great. I will work on it.

**Comment by mirefly** [comment]
@kumar303  Do we still need the link to "/"? (It looks bad to have addon name with a link to "/"). 
I also would like to make sure which way we should show in compare mode
- No version
- Only new version like amo-info-with-extra-dirs: 1.5.0.1-signed
  It is a little confusing since VersionChooser shows both new and old version.
- Both new and old versions like amo-info-with-extra-dirs: 1.3.0...1.5.0.1-signed

Compare mode
![image](https://user-images.githubusercontent.com/4984681/60837622-d5ba7600-a185-11e9-865c-542c4b7065bf.png)

**Comment by wagnerand** [comment]
I would remove the link, or have it point back to the reviewer page.

I am not sure we need to show the version in the top bar (at all). After #758 has landed, the compare dropdown will always be shown, so reviewers can see the version there.
I'd also be fine with showing no version in compare mode and showing it in browse mode.

**Comment by kumar303** [comment]
@mirefly to keep it simple, I suggest only showing the add-on name for now. Toggling between showing a version (in browse mode) and none (in compare mode) would actually be tricky because the `App` component doesn't have any way to figure out what mode it's in.

And, yeah, as mentioned, we will be revisiting this feature when we tackle https://github.com/mozilla/addons-code-manager/issues/758

**Comment by mirefly** [comment]
Thanks @wagnerand @kumar303  In PR #937, I removed the link and only showed the add-on name in both browse and compare modes.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

The add-on name is displayed now both in the browse and the compare page:

![image](https://user-images.githubusercontent.com/31961530/61711256-4bb10680-ad5c-11e9-951e-3dc36cd63798.png)

![image](https://user-images.githubusercontent.com/31961530/61711447-c0844080-ad5c-11e9-9cd5-f15fbc21eaa8.png)
