### ISSUE TITLE
DiffView needs a scrollTo target for global messages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#825]
In #824, we introduced a scrollTo target for global messages into `CodeView` so that the keyboard shortcuts for navigating linter messages would be able to scroll them into view. Because the code that generates global messages lives in both `CodeView` (for browse) and `DiffView` (for compare), we also need a target in `DiffView`. We might be able to create a shared function which can be used by both.

I'll update this issue to add a link to the code added to `CodeView` by #824 after that code lands.

**Comment by bobsilverberg** [comment]
Here's the code that was added to `CodeView` to support this:

https://github.com/mozilla/addons-code-manager/blob/812a3587d58349e7abc00790c7ea356dc6423ef0/src/components/CodeView/index.tsx#L73-L77

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Two problems while testing this today with FF67 - Win10:
- I encounter difficulties while trying to navigate to the Next or Previous linter message or warning making the compare view difficult to test with shortcut keys. 
When I use `z` or `a` the page is very often unresponsive (that is reproducible on both -dev, stage in FF and Chrome). 
This is also reproducible if I simply click another file for Compare page. `Loading diff` is displayed for a while. 

Chrome - empty page 

![empty on Chrome](https://user-images.githubusercontent.com/33448286/60178865-1250ae00-9825-11e9-84fe-5feb3a35a7a9.png)

with FF - after pressing `z`

![FF](https://user-images.githubusercontent.com/33448286/60179188-c81bfc80-9825-11e9-8a03-43ee3d0a2133.png)


- when navigating from another file to one with multiple linter warnings with `z` the top of the page will be displayed instead of the line that contains the linter warning (that is not reproducible for browse view) 
None of the messages inside the file are visible - I see their ids in the URL though. 

![no warning displayed](https://user-images.githubusercontent.com/33448286/60179797-21386000-9827-11e9-987f-fa6213d062b9.gif)

**Comment by kumar303** [comment]
Hi @ioanarusiczki , thanks for all the details
 
>     * I encounter difficulties while trying to navigate to the Next or Previous linter message or warning making the compare view difficult to test with shortcut keys.
>       When I use `z` or `a` the page is very often unresponsive (that is reproducible on both -dev, stage in FF and Chrome).
>       This is also reproducible if I simply click another file for Compare page. `Loading diff` is displayed for a while.

This is probably related to displaying large files which would make it the same issue as https://github.com/mozilla/addons-code-manager/issues/402 Could you try it on smaller files?

> Chrome - empty page
> 
...
> 
> with FF - after pressing `z` [it shows a warning that the web page is slowing down the browser]
> 


Judging from the URLs, these look like the same slow loading problem.

> 
>     * when navigating from another file to one with multiple linter warnings with `z` the top of the page will be displayed instead of the line that contains the linter warning (that is not reproducible for browse view)

Could you file a separate issue with that exact URLs and STR?

>       None of the messages inside the file are visible - I see their ids in the URL though.

That's a known issue that we're working on: https://github.com/mozilla/addons-code-manager/issues/877

**Comment by bobsilverberg** [comment]
I think that many of the problems with the Compare view could be a result of some of the issues I opened yesterday, namely #876 and #877. Also, I believe that PR #839  will also partially address this. I think what you're seeing as a lack of responsiveness when pressing `a` or `z` is that individual messages for a file or line are being navigated, which doesn't cause the screen to update so it looks like nothing is happening, but if you look at the URL you should see it changing.

PR #839 will make it more obvious when a new message is being selected, but it won't help in the cases where we cannot see the messages in the compare view, which is a separate issue.

**Comment by ioanarusiczki** [comment]
I filed my scenario as @kumar303 requested here https://github.com/mozilla/addons-code-manager/issues/887
The other problem I ran into is already filed https://github.com/mozilla/addons-code-manager/issues/402 and also there's https://github.com/mozilla/addons-code-manager/issues/876 filed.
I can mark this verified on -dev, FF67(Win10)
