### ISSUE TITLE
Add a shared GlobalLinterMessages component

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#872]
This is a follow-up to https://github.com/mozilla/addons-code-manager/issues/825 **QA**: please check that issue for context.

The global linter message support in both [`CodeView`](https://github.com/mozilla/addons-code-manager/blob/0e7150a6e4932b7afecfc67f5c859ed4f1eb0e63/src/components/CodeView/index.tsx#L76) and [`DiffView`](https://github.com/mozilla/addons-code-manager/blob/994f9c87c3377f58d878f5c08dc084c0f6fda977/src/components/DiffView/index.tsx#L229-L234) should be rewritten with a common component:

```jsx
<GlobalLinterMessages className={'...'}>
  {globalLinterMessages}
</GlobalLinterMessages>
```

This will ensure that `getCodeLineAnchorID(0)` remains consistent in both, across refactoring. Otherwise, this part of the code is delicate.

**Comment by ioanarusiczki** [comment]
@kumar303 

> This is a follow-up to #825 QA: please check that issue for context.

I believe this means testing regressions for Browse and Compare view?

**Comment by kumar303** [comment]
@ioanarusiczki yes, regression testing specifically for any compare or browse page that shows a linter message at the top of the file (not one on a specific line). Thanks!

**Comment by ioanarusiczki** [comment]
@kumar303 I did not find any regressions on -dev with FF68 (Win10). I could navigate to next or previous changes or warnings using keyboard nav. The linter message/warning is selected. It can be selected from the overview too. 

I did notice an issue for the warnings at the top of the pages but it's not caused by regressions. 
Filed it here https://github.com/mozilla/addons-code-manager/issues/941
