### ISSUE TITLE
Preload next file in Browse to increase perceived performance

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#919]
When reviewing, reviewers often go from top to bottom, from one file to the next. I'd like to propose the following enhancement:

1) When browsing all files, reviewer loads the first file, this takes the normal time it takes
2) Once loading is complete, reviewer tools preload the next N files
3) When reviewer uses `j` to jump to the next file, it is loaded from the cache and we go to (2).
4) When the reviewer selects a random other file, the preload cache is cleared and we go back to (1).

Instead of loading a certain number of files, it could also be full files up to a certain file size.

**Comment by kumar303** [comment]
@kewisch This sounds like a great idea. Is it really the most common case to jump to the next file in order? Would this be in browse mode or compare mode? 

I ask because I'm curious if this is more common than the other cases, which would be:
- jumping to the next linter message (which could be several files away)
- jumping to the next diff, in compare mode

**Comment by kewisch** [comment]
Missed your comment, sorry! In browse mode the most common case is jumping to the next file. In compare mode, the most common case is jumping to the next diff. I think it would be feasible to preload the next file in browse mode, and the next file with a diff in compare mode.

**Comment by ioanarusiczki** [comment]
@kumar303 Please let me know if my test scenarios are alright for this issue.

For Browse View: 
- navigate through files (next, previous file with keyboard navigation) 
- navigate to the next previous linter message using keyboard 
- select randomly a file to view.

In all cases the pages should load promptly/with no delays ?

**Comment by kumar303** [comment]
@ioanarusiczki 

> For Browse View:
> 
>     * navigate through files (next, previous file with keyboard navigation)

Navigating to the *next* file (not previous) using the keyboard should load it without a delay. Clicking a link to the next file should also load it without a delay.
 
>     * navigate to the next previous linter message using keyboard

Pre-loading for this isn't implemented. If you are able to file an issue, please do.

> 
>     * select randomly a file to view.

No pre-loading for this was implemented. There isn't really a way to support pre-loading for this since we don't know what file the reviewer is about to select.

**Comment by ioanarusiczki** [comment]
@kumar303 I tested with a couple of samples and it works for me. 
https://code.addons-dev.allizom.org/en-US/browse/617545/versions/1688861/
https://code.addons-dev.allizom.org/en-US/browse/491860/versions/1528357/
https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/

![Next](https://user-images.githubusercontent.com/33448286/66393311-deb42100-e9da-11e9-8fec-85fa91c1add6.gif)


Verified on dev with FF69(Win10).
