### ISSUE TITLE
Show indication of inserted lines in code overview

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#920]
In compare-mode, it would be nice if the overview showed an indication of changed lines.

After some discussion, it was decided that, for now, we will add code to show an indication of inserted lines in the code overview. This should cover most use cases, as discussed at https://github.com/mozilla/addons-code-manager/issues/920#issuecomment-573083793. A follow-up can be opened in the future if it is determined we need to add an indication for deleted lines as well.

**Comment by EnTeQuAk** [comment]
From an API perspective, that data is already exposed through the `lines_added` / `lines_deleted` properties in `diff` https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#compare

**Comment by bobsilverberg** [comment]
@wagnerand It looks like we can do this, but there is a complication. Currently, the code overview colours lines to indicate the existence of linter messages. So if there is a linter message anywhere in the group of lines represented by a code overview line, that line is coloured, and the colour is based on the severity of the message.

This means that currently, an overview line could be grey, which indicates no message, or it could be red, orange, or a different shade of grey, each of which represents a different severity of linter message.

This issue is suggesting (I believe) adding another set of colours to the mix, where (I assume) some shade of red would be used to indicate a delete change and some shade or green would be used to indicate an insert change. This raises a couple of issues/questions:

1. Which would take precedence if a block of lines includes both linter messages and changes? Also, what if a block contains both insert and delete changes?
2. Is this going to end up being confusing to a user to have so many different possible colours for overview lines, with some of them having different meanings (i.e., a message vs. a change)?

**Comment by wagnerand** [comment]
> This issue is suggesting (I believe) adding another set of colours to the mix, where (I assume) some shade of red would be used to indicate a delete change and some shade or green would be used to indicate an insert change. This raises a couple of issues/questions:

Agreed. If we do want to make it simpler, we could have the same color for both deletions and additions, indicating a general code _change_.

> Which would take precedence if a block of lines includes both linter messages and changes? Also, what if a block contains both insert and delete changes?

The code change should take precedence. I don't have the perfect answer for the second question, maybe we should investigate/pursue the idea above?

> Is this going to end up being confusing to a user to have so many different possible colours for overview lines, with some of them having different meanings (i.e., a message vs. a change)?

I don't believe so, but only time (and feedback will tell). We an also take actions to mitigate that proactively, for example by de-emphasizing lines that don't have any annotations (change, linter message etc).

**Comment by bobsilverberg** [comment]
I discovered that the CodeOverview doesn't even currently sketch out the code for the current diff, but rather sketches out the code for the head version of the file. This works, for the most part, because it allows the CodeOverview to highlight linter messages, because linter messages always correspond to a line in the head version of the file.

Changes, on the other hand, can be deletions, in which case they do not have a corresponding line number in the head version of the file. This means they are not represented in the CodeOverview at all. So in order to fix this issue (highlighting changes in the CodeOverview), we'd need to fix that other issue first/as well. This is quite a large change, as the implementation of the CodeOverview currently relies on it using just plain file content, rather than a diff.

Given all of this, it might behoove us to re-evaluate the priority of this issue, and whether it is in fact a blocker for switching to the new file viewer.

A couple of points to consider:
1. Changes are already highlighted in the diff itself, so can be seen when scrolling through the file.
2. There are also keyboard shortcuts in place that will allow a reviewer to jump from change block to change block, and they might prefer to use that over clicking on the CodeOverview.

**Comment by bobsilverberg** [comment]
@wagnerand Could you please comment on the above, when you get a chance?

**Comment by wagnerand** [comment]
As a stop-gap, could we check whether we could just indicate added lines in the overview? It would still be a bit inaccurate, but better than nothing, I guess?

**Comment by bobsilverberg** [comment]
> As a stop-gap, could we check whether we could just indicate added lines in the overview? It would still be a bit inaccurate, but better than nothing, I guess?

@willdurand and I discussed this and realized that there is really only one use case that won't be covered by this, and a couple of cases that seem like they won't be covered actually will be, or are irrelevant. Here's a summary:

1. A file is deleted. This means that the entire diff would be one large deletion. This would result in an empty CodeOverview, but that seems like a non-issue because if a file has been deleted there should be no reason for a reviewer to need to know the structure of the file. They can still view the contents of the deletion in the code section, but the CodeOverview doesn't seem necessary in this case.

2. Code has been changed. This results in a paired deletion+insertion in the diff. Because the CodeOverview is based on the contents of the most current version of the file, the insertion will be reflected, and we can highlight that in the CodeOverview and link to the insertion. So although the deletion will not be highlighted nor linked to, it's partner will be, which is virtually the same thing.

3. Code has only been deleted. Because the CodeOverview is based on the contents of the most current version of the file, a deletion that is not paired with an insertion will not be reflected in the CodeOverview and there will therefore be no highlighting for this nor any link. This is the single use case that will not be covered if we only highlight and link to insertions. This seems like the least critical thing for a reviewer to know about, as code that has been deleted will not be run in the browser, so will be less likely to have a major impact on a review.

Our recommendation is to proceed with only showing additions in the CodeOverview for now. If it turns out this causes a problem for reviewers a follow-up issue can be filed and we can address it at that time.

@wagnerand Are you in agreement with the above?

**Comment by wagnerand** [comment]
Yes, I agree.

Long-term I'd still like to have deletions reflected in the overview as well. Any code change should be reviewed (and thus indicated in the overview). For example, a developer could remove security checks or constraints.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on dev with FF72(Win10); 
- added or modified lines of code are highlighted with green in the code overview. A green line is also visible on the left side of the file's name. I've noticed an issue while changing versions using the `Compare Versions` button and filed it here https://github.com/mozilla/addons-code-manager/issues/1400

Examples: 
Added lines

https://code.addons-dev.allizom.org/en-US/compare/618623/versions/1690065...1690066/?path=node_modules%2Fweb-animations-js%2Fsrc%2Fscope.js

Modified lines 

https://code.addons-dev.allizom.org/en-US/compare/618623/versions/1690065...1690066/?path=manifest.json#I10
https://code.addons-dev.allizom.org/en-US/compare/618623/versions/1690066...1690067/?path=node_modules%2Fweb-animations-js%2Fsrc%2Fscope.js#I2

- I deleted a file for the next version - loading the compare view the versions API returns a 404

![404 comparing](https://user-images.githubusercontent.com/33448286/72729750-9e973980-3b98-11ea-9ecc-fdf336a12dca.png)

` /reviewers/addon/618623/versions/1690064/?file=node_modules%2Fweb-animations-js%2Fsrc%2Fscope.js&lang=en-US: 404`

Let me know if I should file an issue for this case.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'm going to mark this issue verified because I think that what I said above about the 404 for a deleted file was discussed in https://github.com/mozilla/addons-code-manager/issues/1405.
